package com.matthewperiut.chisel.block;

import net.fabricmc.fabric.api.object.builder.v1.block.FabricBlockSettings;

import net.minecraft.block.Blocks;
import net.minecraft.block.Block;
import net.minecraft.block.PillarBlock;

import static com.matthewperiut.chisel.block.blocks.EzReg.Reg;

public class GeneratedRegister
{
   public static final Block ARRAY_ANDESITE = new Block(FabricBlockSettings.copyOf(Blocks.ANDESITE));
   public static final Block CIRCULAR_ANDESITE = new Block(FabricBlockSettings.copyOf(Blocks.ANDESITE));
   public static final Block CRACKED_ANDESITE = new Block(FabricBlockSettings.copyOf(Blocks.ANDESITE));
   public static final Block CUT_ANDESITE = new Block(FabricBlockSettings.copyOf(Blocks.ANDESITE));
   public static final Block DENT_ANDESITE = new Block(FabricBlockSettings.copyOf(Blocks.ANDESITE));
   public static final Block ENCASED_BRICKS_ANDESITE = new Block(FabricBlockSettings.copyOf(Blocks.ANDESITE));
   public static final Block LARGE_TILE_ANDESITE = new Block(FabricBlockSettings.copyOf(Blocks.ANDESITE));
   public static final Block MOSAIC_ANDESITE = new Block(FabricBlockSettings.copyOf(Blocks.ANDESITE));
   public static final PillarBlock PILLAR_ANDESITE = new PillarBlock(FabricBlockSettings.copyOf(Blocks.ANDESITE));
   public static final Block SLANT_ANDESITE = new Block(FabricBlockSettings.copyOf(Blocks.ANDESITE));
   public static final PillarBlock TWIST_ANDESITE = new PillarBlock(FabricBlockSettings.copyOf(Blocks.ANDESITE));
   public static final Block ZAG_ANDESITE = new Block(FabricBlockSettings.copyOf(Blocks.ANDESITE));
   public static final PillarBlock PILLAR_BLACKSTONE = new PillarBlock(FabricBlockSettings.copyOf(Blocks.BLACKSTONE));
   public static final Block ARRAY_BRICKS = new Block(FabricBlockSettings.copyOf(Blocks.BRICKS));
   public static final Block CIRCULAR_BRICKS = new Block(FabricBlockSettings.copyOf(Blocks.BRICKS));
   public static final Block CRACKED_BRICKS = new Block(FabricBlockSettings.copyOf(Blocks.BRICKS));
   public static final Block CUT_BRICKS = new Block(FabricBlockSettings.copyOf(Blocks.BRICKS));
   public static final Block DENT_BRICKS = new Block(FabricBlockSettings.copyOf(Blocks.BRICKS));
   public static final Block ENCASED_BRICKS_BRICKS = new Block(FabricBlockSettings.copyOf(Blocks.BRICKS));
   public static final Block LARGE_TILE_BRICKS = new Block(FabricBlockSettings.copyOf(Blocks.BRICKS));
   public static final Block MOSAIC_BRICKS = new Block(FabricBlockSettings.copyOf(Blocks.BRICKS));
   public static final PillarBlock PILLAR_BRICKS = new PillarBlock(FabricBlockSettings.copyOf(Blocks.BRICKS));
   public static final Block SLANT_BRICKS = new Block(FabricBlockSettings.copyOf(Blocks.BRICKS));
   public static final PillarBlock TWIST_BRICKS = new PillarBlock(FabricBlockSettings.copyOf(Blocks.BRICKS));
   public static final Block ZAG_BRICKS = new Block(FabricBlockSettings.copyOf(Blocks.BRICKS));
   public static final Block MASONRY_COAL_BLOCK = new Block(FabricBlockSettings.copyOf(Blocks.COAL_BLOCK));
   public static final Block ARRAY_COBBLESTONE = new Block(FabricBlockSettings.copyOf(Blocks.COBBLESTONE));
   public static final Block CIRCULAR_COBBLESTONE = new Block(FabricBlockSettings.copyOf(Blocks.COBBLESTONE));
   public static final Block CRACKED_COBBLESTONE = new Block(FabricBlockSettings.copyOf(Blocks.COBBLESTONE));
   public static final Block CUT_COBBLESTONE = new Block(FabricBlockSettings.copyOf(Blocks.COBBLESTONE));
   public static final Block DENT_COBBLESTONE = new Block(FabricBlockSettings.copyOf(Blocks.COBBLESTONE));
   public static final Block ENCASED_BRICKS_COBBLESTONE = new Block(FabricBlockSettings.copyOf(Blocks.COBBLESTONE));
   public static final Block LARGE_TILE_COBBLESTONE = new Block(FabricBlockSettings.copyOf(Blocks.COBBLESTONE));
   public static final Block MOSAIC_COBBLESTONE = new Block(FabricBlockSettings.copyOf(Blocks.COBBLESTONE));
   public static final PillarBlock PILLAR_COBBLESTONE = new PillarBlock(FabricBlockSettings.copyOf(Blocks.COBBLESTONE));
   public static final Block SLANT_COBBLESTONE = new Block(FabricBlockSettings.copyOf(Blocks.COBBLESTONE));
   public static final PillarBlock TWIST_COBBLESTONE = new PillarBlock(FabricBlockSettings.copyOf(Blocks.COBBLESTONE));
   public static final Block ZAG_COBBLESTONE = new Block(FabricBlockSettings.copyOf(Blocks.COBBLESTONE));
   public static final Block MOSAIC_DEEPSLATE = new Block(FabricBlockSettings.copyOf(Blocks.DEEPSLATE));
   public static final PillarBlock PILLAR_DEEPSLATE = new PillarBlock(FabricBlockSettings.copyOf(Blocks.DEEPSLATE));
   public static final Block SLANT_DEEPSLATE = new Block(FabricBlockSettings.copyOf(Blocks.DEEPSLATE));
   public static final Block ARRAY_DIORITE = new Block(FabricBlockSettings.copyOf(Blocks.DIORITE));
   public static final Block CIRCULAR_DIORITE = new Block(FabricBlockSettings.copyOf(Blocks.DIORITE));
   public static final Block CRACKED_DIORITE = new Block(FabricBlockSettings.copyOf(Blocks.DIORITE));
   public static final Block CUT_DIORITE = new Block(FabricBlockSettings.copyOf(Blocks.DIORITE));
   public static final Block DENT_DIORITE = new Block(FabricBlockSettings.copyOf(Blocks.DIORITE));
   public static final Block ENCASED_BRICKS_DIORITE = new Block(FabricBlockSettings.copyOf(Blocks.DIORITE));
   public static final Block LARGE_TILE_DIORITE = new Block(FabricBlockSettings.copyOf(Blocks.DIORITE));
   public static final Block MOSAIC_DIORITE = new Block(FabricBlockSettings.copyOf(Blocks.DIORITE));
   public static final PillarBlock PILLAR_DIORITE = new PillarBlock(FabricBlockSettings.copyOf(Blocks.DIORITE));
   public static final Block SLANT_DIORITE = new Block(FabricBlockSettings.copyOf(Blocks.DIORITE));
   public static final PillarBlock TWIST_DIORITE = new PillarBlock(FabricBlockSettings.copyOf(Blocks.DIORITE));
   public static final Block ZAG_DIORITE = new Block(FabricBlockSettings.copyOf(Blocks.DIORITE));
   public static final Block ARRAY_END_STONE = new Block(FabricBlockSettings.copyOf(Blocks.END_STONE));
   public static final Block CIRCULAR_END_STONE = new Block(FabricBlockSettings.copyOf(Blocks.END_STONE));
   public static final Block CRACKED_END_STONE = new Block(FabricBlockSettings.copyOf(Blocks.END_STONE));
   public static final Block CUT_END_STONE = new Block(FabricBlockSettings.copyOf(Blocks.END_STONE));
   public static final Block DENT_END_STONE = new Block(FabricBlockSettings.copyOf(Blocks.END_STONE));
   public static final Block ENCASED_BRICKS_END_STONE = new Block(FabricBlockSettings.copyOf(Blocks.END_STONE));
   public static final Block LARGE_TILE_END_STONE = new Block(FabricBlockSettings.copyOf(Blocks.END_STONE));
   public static final Block MOSAIC_END_STONE = new Block(FabricBlockSettings.copyOf(Blocks.END_STONE));
   public static final PillarBlock PILLAR_END_STONE = new PillarBlock(FabricBlockSettings.copyOf(Blocks.END_STONE));
   public static final Block SLANT_END_STONE = new Block(FabricBlockSettings.copyOf(Blocks.END_STONE));
   public static final PillarBlock TWIST_END_STONE = new PillarBlock(FabricBlockSettings.copyOf(Blocks.END_STONE));
   public static final Block ZAG_END_STONE = new Block(FabricBlockSettings.copyOf(Blocks.END_STONE));
   public static final Block ARRAY_GRANITE = new Block(FabricBlockSettings.copyOf(Blocks.GRANITE));
   public static final Block CIRCULAR_GRANITE = new Block(FabricBlockSettings.copyOf(Blocks.GRANITE));
   public static final Block CRACKED_GRANITE = new Block(FabricBlockSettings.copyOf(Blocks.GRANITE));
   public static final Block CUT_GRANITE = new Block(FabricBlockSettings.copyOf(Blocks.GRANITE));
   public static final Block DENT_GRANITE = new Block(FabricBlockSettings.copyOf(Blocks.GRANITE));
   public static final Block ENCASED_BRICKS_GRANITE = new Block(FabricBlockSettings.copyOf(Blocks.GRANITE));
   public static final Block LARGE_TILE_GRANITE = new Block(FabricBlockSettings.copyOf(Blocks.GRANITE));
   public static final Block MOSAIC_GRANITE = new Block(FabricBlockSettings.copyOf(Blocks.GRANITE));
   public static final PillarBlock PILLAR_GRANITE = new PillarBlock(FabricBlockSettings.copyOf(Blocks.GRANITE));
   public static final Block SLANT_GRANITE = new Block(FabricBlockSettings.copyOf(Blocks.GRANITE));
   public static final PillarBlock TWIST_GRANITE = new PillarBlock(FabricBlockSettings.copyOf(Blocks.GRANITE));
   public static final Block ZAG_GRANITE = new Block(FabricBlockSettings.copyOf(Blocks.GRANITE));
   public static final Block MOSAIC_NETHER_BRICK = new Block(FabricBlockSettings.copyOf(Blocks.NETHER_BRICKS));
   public static final PillarBlock PILLAR_NETHER_BRICK = new PillarBlock(FabricBlockSettings.copyOf(Blocks.NETHER_BRICKS));
   public static final Block SLANT_NETHER_BRICK = new Block(FabricBlockSettings.copyOf(Blocks.NETHER_BRICKS));
   public static final Block ARRAY_PURPUR = new Block(FabricBlockSettings.copyOf(Blocks.PURPUR_BLOCK));
   public static final Block CIRCULAR_PURPUR = new Block(FabricBlockSettings.copyOf(Blocks.PURPUR_BLOCK));
   public static final Block CRACKED_PURPUR = new Block(FabricBlockSettings.copyOf(Blocks.PURPUR_BLOCK));
   public static final Block CUT_PURPUR = new Block(FabricBlockSettings.copyOf(Blocks.PURPUR_BLOCK));
   public static final Block DENT_PURPUR = new Block(FabricBlockSettings.copyOf(Blocks.PURPUR_BLOCK));
   public static final Block ENCASED_BRICKS_PURPUR = new Block(FabricBlockSettings.copyOf(Blocks.PURPUR_BLOCK));
   public static final Block LARGE_TILE_PURPUR = new Block(FabricBlockSettings.copyOf(Blocks.PURPUR_BLOCK));
   public static final Block MOSAIC_PURPUR = new Block(FabricBlockSettings.copyOf(Blocks.PURPUR_BLOCK));
   public static final Block SLANT_PURPUR = new Block(FabricBlockSettings.copyOf(Blocks.PURPUR_BLOCK));
   public static final PillarBlock TWIST_PURPUR = new PillarBlock(FabricBlockSettings.copyOf(Blocks.PURPUR_BLOCK));
   public static final Block ZAG_PURPUR = new Block(FabricBlockSettings.copyOf(Blocks.PURPUR_BLOCK));
   public static final Block ARRAY_QUARTZ = new Block(FabricBlockSettings.copyOf(Blocks.QUARTZ_BLOCK));
   public static final Block CIRCULAR_QUARTZ = new Block(FabricBlockSettings.copyOf(Blocks.QUARTZ_BLOCK));
   public static final Block CRACKED_QUARTZ = new Block(FabricBlockSettings.copyOf(Blocks.QUARTZ_BLOCK));
   public static final Block CUT_QUARTZ = new Block(FabricBlockSettings.copyOf(Blocks.QUARTZ_BLOCK));
   public static final Block DENT_QUARTZ = new Block(FabricBlockSettings.copyOf(Blocks.QUARTZ_BLOCK));
   public static final Block ENCASED_BRICKS_QUARTZ = new Block(FabricBlockSettings.copyOf(Blocks.QUARTZ_BLOCK));
   public static final Block LARGE_TILE_QUARTZ = new Block(FabricBlockSettings.copyOf(Blocks.QUARTZ_BLOCK));
   public static final Block MOSAIC_QUARTZ = new Block(FabricBlockSettings.copyOf(Blocks.QUARTZ_BLOCK));
   public static final Block SLANT_QUARTZ = new Block(FabricBlockSettings.copyOf(Blocks.QUARTZ_BLOCK));
   public static final PillarBlock TWIST_QUARTZ = new PillarBlock(FabricBlockSettings.copyOf(Blocks.QUARTZ_BLOCK));
   public static final Block ZAG_QUARTZ = new Block(FabricBlockSettings.copyOf(Blocks.QUARTZ_BLOCK));
   public static final Block ARRAY_RED_SANDSTONE = new Block(FabricBlockSettings.copyOf(Blocks.RED_SANDSTONE));
   public static final Block CIRCULAR_RED_SANDSTONE = new Block(FabricBlockSettings.copyOf(Blocks.RED_SANDSTONE));
   public static final Block CRACKED_RED_SANDSTONE = new Block(FabricBlockSettings.copyOf(Blocks.RED_SANDSTONE));
   public static final Block CUT_RED_SANDSTONE = new Block(FabricBlockSettings.copyOf(Blocks.RED_SANDSTONE));
   public static final Block DENT_RED_SANDSTONE = new Block(FabricBlockSettings.copyOf(Blocks.RED_SANDSTONE));
   public static final Block ENCASED_BRICKS_RED_SANDSTONE = new Block(FabricBlockSettings.copyOf(Blocks.RED_SANDSTONE));
   public static final Block LARGE_TILE_RED_SANDSTONE = new Block(FabricBlockSettings.copyOf(Blocks.RED_SANDSTONE));
   public static final Block MOSAIC_RED_SANDSTONE = new Block(FabricBlockSettings.copyOf(Blocks.RED_SANDSTONE));
   public static final PillarBlock PILLAR_RED_SANDSTONE = new PillarBlock(FabricBlockSettings.copyOf(Blocks.RED_SANDSTONE));
   public static final Block SLANT_RED_SANDSTONE = new Block(FabricBlockSettings.copyOf(Blocks.RED_SANDSTONE));
   public static final PillarBlock TWIST_RED_SANDSTONE = new PillarBlock(FabricBlockSettings.copyOf(Blocks.RED_SANDSTONE));
   public static final Block ZAG_RED_SANDSTONE = new Block(FabricBlockSettings.copyOf(Blocks.RED_SANDSTONE));
   public static final Block ARRAY_SANDSTONE = new Block(FabricBlockSettings.copyOf(Blocks.SANDSTONE));
   public static final Block CIRCULAR_SANDSTONE = new Block(FabricBlockSettings.copyOf(Blocks.SANDSTONE));
   public static final Block CRACKED_SANDSTONE = new Block(FabricBlockSettings.copyOf(Blocks.SANDSTONE));
   public static final Block CUT_SANDSTONE = new Block(FabricBlockSettings.copyOf(Blocks.SANDSTONE));
   public static final Block DENT_SANDSTONE = new Block(FabricBlockSettings.copyOf(Blocks.SANDSTONE));
   public static final Block ENCASED_BRICKS_SANDSTONE = new Block(FabricBlockSettings.copyOf(Blocks.SANDSTONE));
   public static final Block LARGE_TILE_SANDSTONE = new Block(FabricBlockSettings.copyOf(Blocks.SANDSTONE));
   public static final Block MOSAIC_SANDSTONE = new Block(FabricBlockSettings.copyOf(Blocks.SANDSTONE));
   public static final PillarBlock PILLAR_SANDSTONE = new PillarBlock(FabricBlockSettings.copyOf(Blocks.SANDSTONE));
   public static final Block SLANT_SANDSTONE = new Block(FabricBlockSettings.copyOf(Blocks.SANDSTONE));
   public static final PillarBlock TWIST_SANDSTONE = new PillarBlock(FabricBlockSettings.copyOf(Blocks.SANDSTONE));
   public static final Block ZAG_SANDSTONE = new Block(FabricBlockSettings.copyOf(Blocks.SANDSTONE));
   public static final Block ARRAY_STONE = new Block(FabricBlockSettings.copyOf(Blocks.STONE));
   public static final Block CIRCULAR_STONE = new Block(FabricBlockSettings.copyOf(Blocks.STONE));
   public static final Block CRACKED_STONE = new Block(FabricBlockSettings.copyOf(Blocks.STONE));
   public static final Block CUT_STONE = new Block(FabricBlockSettings.copyOf(Blocks.STONE));
   public static final Block DENT_STONE = new Block(FabricBlockSettings.copyOf(Blocks.STONE));
   public static final Block ENCASED_BRICKS_STONE = new Block(FabricBlockSettings.copyOf(Blocks.STONE));
   public static final Block LARGE_TILE_STONE = new Block(FabricBlockSettings.copyOf(Blocks.STONE));
   public static final Block MOSAIC_STONE = new Block(FabricBlockSettings.copyOf(Blocks.STONE));
   public static final PillarBlock PILLAR_STONE = new PillarBlock(FabricBlockSettings.copyOf(Blocks.STONE));
   public static final Block SLANT_STONE = new Block(FabricBlockSettings.copyOf(Blocks.STONE));
   public static final PillarBlock TWIST_STONE = new PillarBlock(FabricBlockSettings.copyOf(Blocks.STONE));
   public static final Block ZAG_STONE = new Block(FabricBlockSettings.copyOf(Blocks.STONE));

    public static void Register()
    {
        Reg("andesite", "array/andesite", ARRAY_ANDESITE);
        Reg("andesite", "circular/andesite", CIRCULAR_ANDESITE);
        Reg("andesite", "cracked/andesite", CRACKED_ANDESITE);
        Reg("andesite", "cut/andesite", CUT_ANDESITE);
        Reg("andesite", "dent/andesite", DENT_ANDESITE);
        Reg("andesite", "encased_bricks/andesite", ENCASED_BRICKS_ANDESITE);
        Reg("andesite", "large_tile/andesite", LARGE_TILE_ANDESITE);
        Reg("andesite", "mosaic/andesite", MOSAIC_ANDESITE);
        Reg("andesite", "pillar/andesite", PILLAR_ANDESITE);
        Reg("andesite", "slant/andesite", SLANT_ANDESITE);
        Reg("andesite", "twist/andesite", TWIST_ANDESITE);
        Reg("andesite", "zag/andesite", ZAG_ANDESITE);
        Reg("blackstone", "pillar/blackstone", PILLAR_BLACKSTONE);
        Reg("bricks", "array/bricks", ARRAY_BRICKS);
        Reg("bricks", "circular/bricks", CIRCULAR_BRICKS);
        Reg("bricks", "cracked/bricks", CRACKED_BRICKS);
        Reg("bricks", "cut/bricks", CUT_BRICKS);
        Reg("bricks", "dent/bricks", DENT_BRICKS);
        Reg("bricks", "encased_bricks/bricks", ENCASED_BRICKS_BRICKS);
        Reg("bricks", "large_tile/bricks", LARGE_TILE_BRICKS);
        Reg("bricks", "mosaic/bricks", MOSAIC_BRICKS);
        Reg("bricks", "pillar/bricks", PILLAR_BRICKS);
        Reg("bricks", "slant/bricks", SLANT_BRICKS);
        Reg("bricks", "twist/bricks", TWIST_BRICKS);
        Reg("bricks", "zag/bricks", ZAG_BRICKS);
        Reg("coal_block", "masonry/coal_block", MASONRY_COAL_BLOCK);
        Reg("cobblestone", "array/cobblestone", ARRAY_COBBLESTONE);
        Reg("cobblestone", "circular/cobblestone", CIRCULAR_COBBLESTONE);
        Reg("cobblestone", "cracked/cobblestone", CRACKED_COBBLESTONE);
        Reg("cobblestone", "cut/cobblestone", CUT_COBBLESTONE);
        Reg("cobblestone", "dent/cobblestone", DENT_COBBLESTONE);
        Reg("cobblestone", "encased_bricks/cobblestone", ENCASED_BRICKS_COBBLESTONE);
        Reg("cobblestone", "large_tile/cobblestone", LARGE_TILE_COBBLESTONE);
        Reg("cobblestone", "mosaic/cobblestone", MOSAIC_COBBLESTONE);
        Reg("cobblestone", "pillar/cobblestone", PILLAR_COBBLESTONE);
        Reg("cobblestone", "slant/cobblestone", SLANT_COBBLESTONE);
        Reg("cobblestone", "twist/cobblestone", TWIST_COBBLESTONE);
        Reg("cobblestone", "zag/cobblestone", ZAG_COBBLESTONE);
        Reg("deepslate", "mosaic/deepslate", MOSAIC_DEEPSLATE);
        Reg("deepslate", "pillar/deepslate", PILLAR_DEEPSLATE);
        Reg("deepslate", "slant/deepslate", SLANT_DEEPSLATE);
        Reg("diorite", "array/diorite", ARRAY_DIORITE);
        Reg("diorite", "circular/diorite", CIRCULAR_DIORITE);
        Reg("diorite", "cracked/diorite", CRACKED_DIORITE);
        Reg("diorite", "cut/diorite", CUT_DIORITE);
        Reg("diorite", "dent/diorite", DENT_DIORITE);
        Reg("diorite", "encased_bricks/diorite", ENCASED_BRICKS_DIORITE);
        Reg("diorite", "large_tile/diorite", LARGE_TILE_DIORITE);
        Reg("diorite", "mosaic/diorite", MOSAIC_DIORITE);
        Reg("diorite", "pillar/diorite", PILLAR_DIORITE);
        Reg("diorite", "slant/diorite", SLANT_DIORITE);
        Reg("diorite", "twist/diorite", TWIST_DIORITE);
        Reg("diorite", "zag/diorite", ZAG_DIORITE);
        Reg("end_stone", "array/end_stone", ARRAY_END_STONE);
        Reg("end_stone", "circular/end_stone", CIRCULAR_END_STONE);
        Reg("end_stone", "cracked/end_stone", CRACKED_END_STONE);
        Reg("end_stone", "cut/end_stone", CUT_END_STONE);
        Reg("end_stone", "dent/end_stone", DENT_END_STONE);
        Reg("end_stone", "encased_bricks/end_stone", ENCASED_BRICKS_END_STONE);
        Reg("end_stone", "large_tile/end_stone", LARGE_TILE_END_STONE);
        Reg("end_stone", "mosaic/end_stone", MOSAIC_END_STONE);
        Reg("end_stone", "pillar/end_stone", PILLAR_END_STONE);
        Reg("end_stone", "slant/end_stone", SLANT_END_STONE);
        Reg("end_stone", "twist/end_stone", TWIST_END_STONE);
        Reg("end_stone", "zag/end_stone", ZAG_END_STONE);
        Reg("granite", "array/granite", ARRAY_GRANITE);
        Reg("granite", "circular/granite", CIRCULAR_GRANITE);
        Reg("granite", "cracked/granite", CRACKED_GRANITE);
        Reg("granite", "cut/granite", CUT_GRANITE);
        Reg("granite", "dent/granite", DENT_GRANITE);
        Reg("granite", "encased_bricks/granite", ENCASED_BRICKS_GRANITE);
        Reg("granite", "large_tile/granite", LARGE_TILE_GRANITE);
        Reg("granite", "mosaic/granite", MOSAIC_GRANITE);
        Reg("granite", "pillar/granite", PILLAR_GRANITE);
        Reg("granite", "slant/granite", SLANT_GRANITE);
        Reg("granite", "twist/granite", TWIST_GRANITE);
        Reg("granite", "zag/granite", ZAG_GRANITE);
        Reg("nether_brick", "mosaic/nether_brick", MOSAIC_NETHER_BRICK);
        Reg("nether_brick", "pillar/nether_brick", PILLAR_NETHER_BRICK);
        Reg("nether_brick", "slant/nether_brick", SLANT_NETHER_BRICK);
        Reg("purpur", "array/purpur", ARRAY_PURPUR);
        Reg("purpur", "circular/purpur", CIRCULAR_PURPUR);
        Reg("purpur", "cracked/purpur", CRACKED_PURPUR);
        Reg("purpur", "cut/purpur", CUT_PURPUR);
        Reg("purpur", "dent/purpur", DENT_PURPUR);
        Reg("purpur", "encased_bricks/purpur", ENCASED_BRICKS_PURPUR);
        Reg("purpur", "large_tile/purpur", LARGE_TILE_PURPUR);
        Reg("purpur", "mosaic/purpur", MOSAIC_PURPUR);
        Reg("purpur", "slant/purpur", SLANT_PURPUR);
        Reg("purpur", "twist/purpur", TWIST_PURPUR);
        Reg("purpur", "zag/purpur", ZAG_PURPUR);
        Reg("quartz", "array/quartz", ARRAY_QUARTZ);
        Reg("quartz", "circular/quartz", CIRCULAR_QUARTZ);
        Reg("quartz", "cracked/quartz", CRACKED_QUARTZ);
        Reg("quartz", "cut/quartz", CUT_QUARTZ);
        Reg("quartz", "dent/quartz", DENT_QUARTZ);
        Reg("quartz", "encased_bricks/quartz", ENCASED_BRICKS_QUARTZ);
        Reg("quartz", "large_tile/quartz", LARGE_TILE_QUARTZ);
        Reg("quartz", "mosaic/quartz", MOSAIC_QUARTZ);
        Reg("quartz", "slant/quartz", SLANT_QUARTZ);
        Reg("quartz", "twist/quartz", TWIST_QUARTZ);
        Reg("quartz", "zag/quartz", ZAG_QUARTZ);
        Reg("red_sandstone", "array/red_sandstone", ARRAY_RED_SANDSTONE);
        Reg("red_sandstone", "circular/red_sandstone", CIRCULAR_RED_SANDSTONE);
        Reg("red_sandstone", "cracked/red_sandstone", CRACKED_RED_SANDSTONE);
        Reg("red_sandstone", "cut/red_sandstone", CUT_RED_SANDSTONE);
        Reg("red_sandstone", "dent/red_sandstone", DENT_RED_SANDSTONE);
        Reg("red_sandstone", "encased_bricks/red_sandstone", ENCASED_BRICKS_RED_SANDSTONE);
        Reg("red_sandstone", "large_tile/red_sandstone", LARGE_TILE_RED_SANDSTONE);
        Reg("red_sandstone", "mosaic/red_sandstone", MOSAIC_RED_SANDSTONE);
        Reg("red_sandstone", "pillar/red_sandstone", PILLAR_RED_SANDSTONE);
        Reg("red_sandstone", "slant/red_sandstone", SLANT_RED_SANDSTONE);
        Reg("red_sandstone", "twist/red_sandstone", TWIST_RED_SANDSTONE);
        Reg("red_sandstone", "zag/red_sandstone", ZAG_RED_SANDSTONE);
        Reg("sandstone", "array/sandstone", ARRAY_SANDSTONE);
        Reg("sandstone", "circular/sandstone", CIRCULAR_SANDSTONE);
        Reg("sandstone", "cracked/sandstone", CRACKED_SANDSTONE);
        Reg("sandstone", "cut/sandstone", CUT_SANDSTONE);
        Reg("sandstone", "dent/sandstone", DENT_SANDSTONE);
        Reg("sandstone", "encased_bricks/sandstone", ENCASED_BRICKS_SANDSTONE);
        Reg("sandstone", "large_tile/sandstone", LARGE_TILE_SANDSTONE);
        Reg("sandstone", "mosaic/sandstone", MOSAIC_SANDSTONE);
        Reg("sandstone", "pillar/sandstone", PILLAR_SANDSTONE);
        Reg("sandstone", "slant/sandstone", SLANT_SANDSTONE);
        Reg("sandstone", "twist/sandstone", TWIST_SANDSTONE);
        Reg("sandstone", "zag/sandstone", ZAG_SANDSTONE);
        Reg("stone", "array/stone", ARRAY_STONE);
        Reg("stone", "circular/stone", CIRCULAR_STONE);
        Reg("stone", "cracked/stone", CRACKED_STONE);
        Reg("stone", "cut/stone", CUT_STONE);
        Reg("stone", "dent/stone", DENT_STONE);
        Reg("stone", "encased_bricks/stone", ENCASED_BRICKS_STONE);
        Reg("stone", "large_tile/stone", LARGE_TILE_STONE);
        Reg("stone", "mosaic/stone", MOSAIC_STONE);
        Reg("stone", "pillar/stone", PILLAR_STONE);
        Reg("stone", "slant/stone", SLANT_STONE);
        Reg("stone", "twist/stone", TWIST_STONE);
        Reg("stone", "zag/stone", ZAG_STONE);
    }
}