package com.matthewperiut.chisel.block;

import com.matthewperiut.chisel.block.blocks.RedstonePillarBlock;
import net.fabricmc.fabric.api.object.builder.v1.block.FabricBlockSettings;

import net.minecraft.block.Blocks;
import net.minecraft.block.Block;
import net.minecraft.block.PillarBlock;
import net.minecraft.block.RedstoneBlock;

import static com.matthewperiut.chisel.block.blocks.EzReg.Reg;

public class GeneratedRegister
{
   public static final Block ARRAY_ANDESITE = new Block(FabricBlockSettings.copyOf(Blocks.ANDESITE));
   public static final Block BRAID_ANDESITE = new Block(FabricBlockSettings.copyOf(Blocks.ANDESITE));
   public static final Block CHAOTIC_BRICKS_ANDESITE = new Block(FabricBlockSettings.copyOf(Blocks.ANDESITE));
   public static final Block CHAOTIC_MEDIUM_ANDESITE = new Block(FabricBlockSettings.copyOf(Blocks.ANDESITE));
   public static final Block CHAOTIC_SMALL_ANDESITE = new Block(FabricBlockSettings.copyOf(Blocks.ANDESITE));
   public static final Block CIRCULAR_ANDESITE = new Block(FabricBlockSettings.copyOf(Blocks.ANDESITE));
   public static final Block CRACKED_ANDESITE = new Block(FabricBlockSettings.copyOf(Blocks.ANDESITE));
   public static final Block CRACKED_BRICKS_ANDESITE = new Block(FabricBlockSettings.copyOf(Blocks.ANDESITE));
   public static final Block CUT_ANDESITE = new Block(FabricBlockSettings.copyOf(Blocks.ANDESITE));
   public static final Block DENT_ANDESITE = new Block(FabricBlockSettings.copyOf(Blocks.ANDESITE));
   public static final Block ENCASED_BRICKS_ANDESITE = new Block(FabricBlockSettings.copyOf(Blocks.ANDESITE));
   public static final Block FRENCH_ANDESITE = new Block(FabricBlockSettings.copyOf(Blocks.ANDESITE));
   public static final Block JELLYBEAN_ANDESITE = new Block(FabricBlockSettings.copyOf(Blocks.ANDESITE));
   public static final Block LARGE_TILE_ANDESITE = new Block(FabricBlockSettings.copyOf(Blocks.ANDESITE));
   public static final Block LAYER_ANDESITE = new Block(FabricBlockSettings.copyOf(Blocks.ANDESITE));
   public static final Block MOSAIC_ANDESITE = new Block(FabricBlockSettings.copyOf(Blocks.ANDESITE));
   public static final Block ORNATE_ANDESITE = new Block(FabricBlockSettings.copyOf(Blocks.ANDESITE));
   public static final Block PANEL_ANDESITE = new Block(FabricBlockSettings.copyOf(Blocks.ANDESITE));
   public static final PillarBlock PILLAR_ANDESITE = new PillarBlock(FabricBlockSettings.copyOf(Blocks.ANDESITE));
   public static final Block PRISM_ANDESITE = new Block(FabricBlockSettings.copyOf(Blocks.ANDESITE));
   public static final Block RAW_ANDESITE = new Block(FabricBlockSettings.copyOf(Blocks.ANDESITE));
   public static final Block ROAD_ANDESITE = new Block(FabricBlockSettings.copyOf(Blocks.ANDESITE));
   public static final Block SLANT_ANDESITE = new Block(FabricBlockSettings.copyOf(Blocks.ANDESITE));
   public static final Block SMALL_BRICKS_ANDESITE = new Block(FabricBlockSettings.copyOf(Blocks.ANDESITE));
   public static final Block SOFT_BRICKS_ANDESITE = new Block(FabricBlockSettings.copyOf(Blocks.ANDESITE));
   public static final Block SOLID_BRICKS_ANDESITE = new Block(FabricBlockSettings.copyOf(Blocks.ANDESITE));
   public static final Block TILES_MEDIUM_ANDESITE = new Block(FabricBlockSettings.copyOf(Blocks.ANDESITE));
   public static final Block TILES_SMALL_ANDESITE = new Block(FabricBlockSettings.copyOf(Blocks.ANDESITE));
   public static final Block TRIPLE_BRICKS_ANDESITE = new Block(FabricBlockSettings.copyOf(Blocks.ANDESITE));
   public static final PillarBlock TWIST_ANDESITE = new PillarBlock(FabricBlockSettings.copyOf(Blocks.ANDESITE));
   public static final Block WEAVER_ANDESITE = new Block(FabricBlockSettings.copyOf(Blocks.ANDESITE));
   public static final Block ZAG_ANDESITE = new Block(FabricBlockSettings.copyOf(Blocks.ANDESITE));
   public static final PillarBlock PILLAR_BLACKSTONE = new PillarBlock(FabricBlockSettings.copyOf(Blocks.BLACKSTONE));
   public static final Block ARRAY_BRICKS = new Block(FabricBlockSettings.copyOf(Blocks.BRICKS));
   public static final Block BRAID_BRICKS = new Block(FabricBlockSettings.copyOf(Blocks.BRICKS));
   public static final Block CHAOTIC_BRICKS_BRICKS = new Block(FabricBlockSettings.copyOf(Blocks.BRICKS));
   public static final Block CHAOTIC_MEDIUM_BRICKS = new Block(FabricBlockSettings.copyOf(Blocks.BRICKS));
   public static final Block CHAOTIC_SMALL_BRICKS = new Block(FabricBlockSettings.copyOf(Blocks.BRICKS));
   public static final Block CIRCULAR_BRICKS = new Block(FabricBlockSettings.copyOf(Blocks.BRICKS));
   public static final Block CRACKED_BRICKS = new Block(FabricBlockSettings.copyOf(Blocks.BRICKS));
   public static final Block CRACKED_BRICKS_BRICKS = new Block(FabricBlockSettings.copyOf(Blocks.BRICKS));
   public static final Block CUT_BRICKS = new Block(FabricBlockSettings.copyOf(Blocks.BRICKS));
   public static final Block DENT_BRICKS = new Block(FabricBlockSettings.copyOf(Blocks.BRICKS));
   public static final Block ENCASED_BRICKS_BRICKS = new Block(FabricBlockSettings.copyOf(Blocks.BRICKS));
   public static final Block FRENCH_BRICKS = new Block(FabricBlockSettings.copyOf(Blocks.BRICKS));
   public static final Block JELLYBEAN_BRICKS = new Block(FabricBlockSettings.copyOf(Blocks.BRICKS));
   public static final Block LARGE_TILE_BRICKS = new Block(FabricBlockSettings.copyOf(Blocks.BRICKS));
   public static final Block LAYER_BRICKS = new Block(FabricBlockSettings.copyOf(Blocks.BRICKS));
   public static final Block MOSAIC_BRICKS = new Block(FabricBlockSettings.copyOf(Blocks.BRICKS));
   public static final Block ORNATE_BRICKS = new Block(FabricBlockSettings.copyOf(Blocks.BRICKS));
   public static final Block PANEL_BRICKS = new Block(FabricBlockSettings.copyOf(Blocks.BRICKS));
   public static final PillarBlock PILLAR_BRICKS = new PillarBlock(FabricBlockSettings.copyOf(Blocks.BRICKS));
   public static final Block PRISM_BRICKS = new Block(FabricBlockSettings.copyOf(Blocks.BRICKS));
   public static final Block RAW_BRICKS = new Block(FabricBlockSettings.copyOf(Blocks.BRICKS));
   public static final Block ROAD_BRICKS = new Block(FabricBlockSettings.copyOf(Blocks.BRICKS));
   public static final Block SLANT_BRICKS = new Block(FabricBlockSettings.copyOf(Blocks.BRICKS));
   public static final Block SMALL_BRICKS_BRICKS = new Block(FabricBlockSettings.copyOf(Blocks.BRICKS));
   public static final Block SOFT_BRICKS_BRICKS = new Block(FabricBlockSettings.copyOf(Blocks.BRICKS));
   public static final Block SOLID_BRICKS_BRICKS = new Block(FabricBlockSettings.copyOf(Blocks.BRICKS));
   public static final Block TILES_MEDIUM_BRICKS = new Block(FabricBlockSettings.copyOf(Blocks.BRICKS));
   public static final Block TILES_SMALL_BRICKS = new Block(FabricBlockSettings.copyOf(Blocks.BRICKS));
   public static final Block TRIPLE_BRICKS_BRICKS = new Block(FabricBlockSettings.copyOf(Blocks.BRICKS));
   public static final PillarBlock TWIST_BRICKS = new PillarBlock(FabricBlockSettings.copyOf(Blocks.BRICKS));
   public static final Block WEAVER_BRICKS = new Block(FabricBlockSettings.copyOf(Blocks.BRICKS));
   public static final Block ZAG_BRICKS = new Block(FabricBlockSettings.copyOf(Blocks.BRICKS));
   public static final Block ARRAY_COAL_BLOCK = new Block(FabricBlockSettings.copyOf(Blocks.COAL_BLOCK));
   public static final Block BRAID_COAL_BLOCK = new Block(FabricBlockSettings.copyOf(Blocks.COAL_BLOCK));
   public static final Block CHAOTIC_BRICKS_COAL_BLOCK = new Block(FabricBlockSettings.copyOf(Blocks.COAL_BLOCK));
   public static final Block CHAOTIC_MEDIUM_COAL_BLOCK = new Block(FabricBlockSettings.copyOf(Blocks.COAL_BLOCK));
   public static final Block CHAOTIC_SMALL_COAL_BLOCK = new Block(FabricBlockSettings.copyOf(Blocks.COAL_BLOCK));
   public static final Block CIRCULAR_COAL_BLOCK = new Block(FabricBlockSettings.copyOf(Blocks.COAL_BLOCK));
   public static final Block CRACKED_COAL_BLOCK = new Block(FabricBlockSettings.copyOf(Blocks.COAL_BLOCK));
   public static final Block CRACKED_BRICKS_COAL_BLOCK = new Block(FabricBlockSettings.copyOf(Blocks.COAL_BLOCK));
   public static final Block CUT_COAL_BLOCK = new Block(FabricBlockSettings.copyOf(Blocks.COAL_BLOCK));
   public static final Block DENT_COAL_BLOCK = new Block(FabricBlockSettings.copyOf(Blocks.COAL_BLOCK));
   public static final Block ENCASED_BRICKS_COAL_BLOCK = new Block(FabricBlockSettings.copyOf(Blocks.COAL_BLOCK));
   public static final Block FRENCH_COAL_BLOCK = new Block(FabricBlockSettings.copyOf(Blocks.COAL_BLOCK));
   public static final Block JELLYBEAN_COAL_BLOCK = new Block(FabricBlockSettings.copyOf(Blocks.COAL_BLOCK));
   public static final Block LARGE_BRICKS_COAL_BLOCK = new Block(FabricBlockSettings.copyOf(Blocks.COAL_BLOCK));
   public static final Block LARGE_TILE_COAL_BLOCK = new Block(FabricBlockSettings.copyOf(Blocks.COAL_BLOCK));
   public static final Block MASONRY_COAL_BLOCK = new Block(FabricBlockSettings.copyOf(Blocks.COAL_BLOCK));
   public static final Block MOSAIC_COAL_BLOCK = new Block(FabricBlockSettings.copyOf(Blocks.COAL_BLOCK));
   public static final Block ORNATE_COAL_BLOCK = new Block(FabricBlockSettings.copyOf(Blocks.COAL_BLOCK));
   public static final Block PANEL_COAL_BLOCK = new Block(FabricBlockSettings.copyOf(Blocks.COAL_BLOCK));
   public static final PillarBlock PILLAR_COAL_BLOCK = new PillarBlock(FabricBlockSettings.copyOf(Blocks.COAL_BLOCK));
   public static final Block PRISM_COAL_BLOCK = new Block(FabricBlockSettings.copyOf(Blocks.COAL_BLOCK));
   public static final Block RAW_COAL_BLOCK = new Block(FabricBlockSettings.copyOf(Blocks.COAL_BLOCK));
   public static final Block ROAD_COAL_BLOCK = new Block(FabricBlockSettings.copyOf(Blocks.COAL_BLOCK));
   public static final Block SLANT_COAL_BLOCK = new Block(FabricBlockSettings.copyOf(Blocks.COAL_BLOCK));
   public static final Block SMALL_BRICKS_COAL_BLOCK = new Block(FabricBlockSettings.copyOf(Blocks.COAL_BLOCK));
   public static final Block SOFT_BRICKS_COAL_BLOCK = new Block(FabricBlockSettings.copyOf(Blocks.COAL_BLOCK));
   public static final Block SOLID_BRICKS_COAL_BLOCK = new Block(FabricBlockSettings.copyOf(Blocks.COAL_BLOCK));
   public static final Block TILES_MEDIUM_COAL_BLOCK = new Block(FabricBlockSettings.copyOf(Blocks.COAL_BLOCK));
   public static final Block TILES_SMALL_COAL_BLOCK = new Block(FabricBlockSettings.copyOf(Blocks.COAL_BLOCK));
   public static final Block TRIPLE_BRICKS_COAL_BLOCK = new Block(FabricBlockSettings.copyOf(Blocks.COAL_BLOCK));
   public static final PillarBlock TWIST_COAL_BLOCK = new PillarBlock(FabricBlockSettings.copyOf(Blocks.COAL_BLOCK));
   public static final Block WEAVER_COAL_BLOCK = new Block(FabricBlockSettings.copyOf(Blocks.COAL_BLOCK));
   public static final Block ZAG_COAL_BLOCK = new Block(FabricBlockSettings.copyOf(Blocks.COAL_BLOCK));
   public static final Block ARRAY_COBBLESTONE = new Block(FabricBlockSettings.copyOf(Blocks.COBBLESTONE));
   public static final Block BRAID_COBBLESTONE = new Block(FabricBlockSettings.copyOf(Blocks.COBBLESTONE));
   public static final Block CHAOTIC_BRICKS_COBBLESTONE = new Block(FabricBlockSettings.copyOf(Blocks.COBBLESTONE));
   public static final Block CHAOTIC_MEDIUM_COBBLESTONE = new Block(FabricBlockSettings.copyOf(Blocks.COBBLESTONE));
   public static final Block CHAOTIC_SMALL_COBBLESTONE = new Block(FabricBlockSettings.copyOf(Blocks.COBBLESTONE));
   public static final Block CIRCULAR_COBBLESTONE = new Block(FabricBlockSettings.copyOf(Blocks.COBBLESTONE));
   public static final Block CRACKED_COBBLESTONE = new Block(FabricBlockSettings.copyOf(Blocks.COBBLESTONE));
   public static final Block CRACKED_BRICKS_COBBLESTONE = new Block(FabricBlockSettings.copyOf(Blocks.COBBLESTONE));
   public static final Block CUT_COBBLESTONE = new Block(FabricBlockSettings.copyOf(Blocks.COBBLESTONE));
   public static final Block DENT_COBBLESTONE = new Block(FabricBlockSettings.copyOf(Blocks.COBBLESTONE));
   public static final Block ENCASED_BRICKS_COBBLESTONE = new Block(FabricBlockSettings.copyOf(Blocks.COBBLESTONE));
   public static final Block FRENCH_COBBLESTONE = new Block(FabricBlockSettings.copyOf(Blocks.COBBLESTONE));
   public static final Block JELLYBEAN_COBBLESTONE = new Block(FabricBlockSettings.copyOf(Blocks.COBBLESTONE));
   public static final Block LARGE_TILE_COBBLESTONE = new Block(FabricBlockSettings.copyOf(Blocks.COBBLESTONE));
   public static final Block LAYER_COBBLESTONE = new Block(FabricBlockSettings.copyOf(Blocks.COBBLESTONE));
   public static final Block MOSAIC_COBBLESTONE = new Block(FabricBlockSettings.copyOf(Blocks.COBBLESTONE));
   public static final Block ORNATE_COBBLESTONE = new Block(FabricBlockSettings.copyOf(Blocks.COBBLESTONE));
   public static final Block PANEL_COBBLESTONE = new Block(FabricBlockSettings.copyOf(Blocks.COBBLESTONE));
   public static final PillarBlock PILLAR_COBBLESTONE = new PillarBlock(FabricBlockSettings.copyOf(Blocks.COBBLESTONE));
   public static final Block PRISM_COBBLESTONE = new Block(FabricBlockSettings.copyOf(Blocks.COBBLESTONE));
   public static final Block RAW_COBBLESTONE = new Block(FabricBlockSettings.copyOf(Blocks.COBBLESTONE));
   public static final Block ROAD_COBBLESTONE = new Block(FabricBlockSettings.copyOf(Blocks.COBBLESTONE));
   public static final Block SLANT_COBBLESTONE = new Block(FabricBlockSettings.copyOf(Blocks.COBBLESTONE));
   public static final Block SMALL_BRICKS_COBBLESTONE = new Block(FabricBlockSettings.copyOf(Blocks.COBBLESTONE));
   public static final Block SOFT_BRICKS_COBBLESTONE = new Block(FabricBlockSettings.copyOf(Blocks.COBBLESTONE));
   public static final Block SOLID_BRICKS_COBBLESTONE = new Block(FabricBlockSettings.copyOf(Blocks.COBBLESTONE));
   public static final Block TILES_MEDIUM_COBBLESTONE = new Block(FabricBlockSettings.copyOf(Blocks.COBBLESTONE));
   public static final Block TILES_SMALL_COBBLESTONE = new Block(FabricBlockSettings.copyOf(Blocks.COBBLESTONE));
   public static final Block TRIPLE_BRICKS_COBBLESTONE = new Block(FabricBlockSettings.copyOf(Blocks.COBBLESTONE));
   public static final PillarBlock TWIST_COBBLESTONE = new PillarBlock(FabricBlockSettings.copyOf(Blocks.COBBLESTONE));
   public static final Block WEAVER_COBBLESTONE = new Block(FabricBlockSettings.copyOf(Blocks.COBBLESTONE));
   public static final Block ZAG_COBBLESTONE = new Block(FabricBlockSettings.copyOf(Blocks.COBBLESTONE));
   public static final Block MOSAIC_DEEPSLATE = new Block(FabricBlockSettings.copyOf(Blocks.DEEPSLATE));
   public static final PillarBlock PILLAR_DEEPSLATE = new PillarBlock(FabricBlockSettings.copyOf(Blocks.DEEPSLATE));
   public static final Block SLANT_DEEPSLATE = new Block(FabricBlockSettings.copyOf(Blocks.DEEPSLATE));
   public static final Block BISMUTH_DIAMOND_BLOCK = new Block(FabricBlockSettings.copyOf(Blocks.DIAMOND_BLOCK));
   public static final Block CELLS_DIAMOND_BLOCK = new Block(FabricBlockSettings.copyOf(Blocks.DIAMOND_BLOCK));
   public static final Block CRUSHED_DIAMOND_BLOCK = new Block(FabricBlockSettings.copyOf(Blocks.DIAMOND_BLOCK));
   public static final Block EMBOSSED_DIAMOND_BLOCK = new Block(FabricBlockSettings.copyOf(Blocks.DIAMOND_BLOCK));
   public static final Block FOUR_DIAMOND_BLOCK = new Block(FabricBlockSettings.copyOf(Blocks.DIAMOND_BLOCK));
   public static final Block FOURORNATE_DIAMOND_BLOCK = new Block(FabricBlockSettings.copyOf(Blocks.DIAMOND_BLOCK));
   public static final Block GEM_DIAMOND_BLOCK = new Block(FabricBlockSettings.copyOf(Blocks.DIAMOND_BLOCK));
   public static final Block ORNATELAYER_DIAMOND_BLOCK = new Block(FabricBlockSettings.copyOf(Blocks.DIAMOND_BLOCK));
   public static final Block SIMPLE_DIAMOND_BLOCK = new Block(FabricBlockSettings.copyOf(Blocks.DIAMOND_BLOCK));
   public static final Block SPACE_DIAMOND_BLOCK = new Block(FabricBlockSettings.copyOf(Blocks.DIAMOND_BLOCK));
   public static final Block SPACEBLACK_DIAMOND_BLOCK = new Block(FabricBlockSettings.copyOf(Blocks.DIAMOND_BLOCK));
   public static final Block ZELDA_DIAMOND_BLOCK = new Block(FabricBlockSettings.copyOf(Blocks.DIAMOND_BLOCK));
   public static final Block ARRAY_DIORITE = new Block(FabricBlockSettings.copyOf(Blocks.DIORITE));
   public static final Block BRAID_DIORITE = new Block(FabricBlockSettings.copyOf(Blocks.DIORITE));
   public static final Block CHAOTIC_BRICKS_DIORITE = new Block(FabricBlockSettings.copyOf(Blocks.DIORITE));
   public static final Block CHAOTIC_MEDIUM_DIORITE = new Block(FabricBlockSettings.copyOf(Blocks.DIORITE));
   public static final Block CHAOTIC_SMALL_DIORITE = new Block(FabricBlockSettings.copyOf(Blocks.DIORITE));
   public static final Block CIRCULAR_DIORITE = new Block(FabricBlockSettings.copyOf(Blocks.DIORITE));
   public static final Block CRACKED_DIORITE = new Block(FabricBlockSettings.copyOf(Blocks.DIORITE));
   public static final Block CRACKED_BRICKS_DIORITE = new Block(FabricBlockSettings.copyOf(Blocks.DIORITE));
   public static final Block CUT_DIORITE = new Block(FabricBlockSettings.copyOf(Blocks.DIORITE));
   public static final Block DENT_DIORITE = new Block(FabricBlockSettings.copyOf(Blocks.DIORITE));
   public static final Block ENCASED_BRICKS_DIORITE = new Block(FabricBlockSettings.copyOf(Blocks.DIORITE));
   public static final Block FRENCH_DIORITE = new Block(FabricBlockSettings.copyOf(Blocks.DIORITE));
   public static final Block JELLYBEAN_DIORITE = new Block(FabricBlockSettings.copyOf(Blocks.DIORITE));
   public static final Block LARGE_TILE_DIORITE = new Block(FabricBlockSettings.copyOf(Blocks.DIORITE));
   public static final Block LAYER_DIORITE = new Block(FabricBlockSettings.copyOf(Blocks.DIORITE));
   public static final Block MOSAIC_DIORITE = new Block(FabricBlockSettings.copyOf(Blocks.DIORITE));
   public static final Block ORNATE_DIORITE = new Block(FabricBlockSettings.copyOf(Blocks.DIORITE));
   public static final Block PANEL_DIORITE = new Block(FabricBlockSettings.copyOf(Blocks.DIORITE));
   public static final PillarBlock PILLAR_DIORITE = new PillarBlock(FabricBlockSettings.copyOf(Blocks.DIORITE));
   public static final Block PRISM_DIORITE = new Block(FabricBlockSettings.copyOf(Blocks.DIORITE));
   public static final Block RAW_DIORITE = new Block(FabricBlockSettings.copyOf(Blocks.DIORITE));
   public static final Block ROAD_DIORITE = new Block(FabricBlockSettings.copyOf(Blocks.DIORITE));
   public static final Block SLANT_DIORITE = new Block(FabricBlockSettings.copyOf(Blocks.DIORITE));
   public static final Block SMALL_BRICKS_DIORITE = new Block(FabricBlockSettings.copyOf(Blocks.DIORITE));
   public static final Block SOFT_BRICKS_DIORITE = new Block(FabricBlockSettings.copyOf(Blocks.DIORITE));
   public static final Block SOLID_BRICKS_DIORITE = new Block(FabricBlockSettings.copyOf(Blocks.DIORITE));
   public static final Block TILES_MEDIUM_DIORITE = new Block(FabricBlockSettings.copyOf(Blocks.DIORITE));
   public static final Block TILES_SMALL_DIORITE = new Block(FabricBlockSettings.copyOf(Blocks.DIORITE));
   public static final Block TRIPLE_BRICKS_DIORITE = new Block(FabricBlockSettings.copyOf(Blocks.DIORITE));
   public static final PillarBlock TWIST_DIORITE = new PillarBlock(FabricBlockSettings.copyOf(Blocks.DIORITE));
   public static final Block WEAVER_DIORITE = new Block(FabricBlockSettings.copyOf(Blocks.DIORITE));
   public static final Block ZAG_DIORITE = new Block(FabricBlockSettings.copyOf(Blocks.DIORITE));
   public static final Block BRICKS_DIRT = new Block(FabricBlockSettings.copyOf(Blocks.DIRT));
   public static final Block BRICKS2_DIRT = new Block(FabricBlockSettings.copyOf(Blocks.DIRT));
   public static final Block BRICKS3_DIRT = new Block(FabricBlockSettings.copyOf(Blocks.DIRT));
   public static final Block CHUNKY_DIRT = new Block(FabricBlockSettings.copyOf(Blocks.DIRT));
   public static final Block COBBLE_DIRT = new Block(FabricBlockSettings.copyOf(Blocks.DIRT));
   public static final Block HAPPY_DIRT = new Block(FabricBlockSettings.copyOf(Blocks.DIRT));
   public static final Block HORIZONTAL_DIRT = new Block(FabricBlockSettings.copyOf(Blocks.DIRT));
   public static final Block LAYER_DIRT = new Block(FabricBlockSettings.copyOf(Blocks.DIRT));
   public static final Block PANEL_DIRT = new Block(FabricBlockSettings.copyOf(Blocks.DIRT));
   public static final Block REINFORCED_DIRT = new Block(FabricBlockSettings.copyOf(Blocks.DIRT));
   public static final Block REINFORCEDCOBBLE_DIRT = new Block(FabricBlockSettings.copyOf(Blocks.DIRT));
   public static final Block VERTICAL_DIRT = new Block(FabricBlockSettings.copyOf(Blocks.DIRT));
   public static final Block BISMUTH_EMERALD_BLOCK = new Block(FabricBlockSettings.copyOf(Blocks.EMERALD_BLOCK));
   public static final Block CELLS_EMERALD_BLOCK = new Block(FabricBlockSettings.copyOf(Blocks.EMERALD_BLOCK));
   public static final Block CHUNKY_EMERALD_BLOCK = new Block(FabricBlockSettings.copyOf(Blocks.EMERALD_BLOCK));
   public static final Block CIRCULAR_EMERALD_BLOCK = new Block(FabricBlockSettings.copyOf(Blocks.EMERALD_BLOCK));
   public static final Block FOUR_EMERALD_BLOCK = new Block(FabricBlockSettings.copyOf(Blocks.EMERALD_BLOCK));
   public static final Block FOURORNATE_EMERALD_BLOCK = new Block(FabricBlockSettings.copyOf(Blocks.EMERALD_BLOCK));
   public static final Block GOLDBORDER_EMERALD_BLOCK = new Block(FabricBlockSettings.copyOf(Blocks.EMERALD_BLOCK));
   public static final Block MASONRY_EMERALD_BLOCK = new Block(FabricBlockSettings.copyOf(Blocks.EMERALD_BLOCK));
   public static final Block ORNATE_EMERALD_BLOCK = new Block(FabricBlockSettings.copyOf(Blocks.EMERALD_BLOCK));
   public static final Block PANEL_EMERALD_BLOCK = new Block(FabricBlockSettings.copyOf(Blocks.EMERALD_BLOCK));
   public static final Block PANELCLASSIC_EMERALD_BLOCK = new Block(FabricBlockSettings.copyOf(Blocks.EMERALD_BLOCK));
   public static final Block PRISM_EMERALD_BLOCK = new Block(FabricBlockSettings.copyOf(Blocks.EMERALD_BLOCK));
   public static final Block SMOOTH_EMERALD_BLOCK = new Block(FabricBlockSettings.copyOf(Blocks.EMERALD_BLOCK));
   public static final Block ZELDA_EMERALD_BLOCK = new Block(FabricBlockSettings.copyOf(Blocks.EMERALD_BLOCK));
   public static final Block ARRAY_END_STONE = new Block(FabricBlockSettings.copyOf(Blocks.END_STONE));
   public static final Block BRAID_END_STONE = new Block(FabricBlockSettings.copyOf(Blocks.END_STONE));
   public static final Block CHAOTIC_BRICKS_END_STONE = new Block(FabricBlockSettings.copyOf(Blocks.END_STONE));
   public static final Block CHAOTIC_MEDIUM_END_STONE = new Block(FabricBlockSettings.copyOf(Blocks.END_STONE));
   public static final Block CHAOTIC_SMALL_END_STONE = new Block(FabricBlockSettings.copyOf(Blocks.END_STONE));
   public static final Block CIRCULAR_END_STONE = new Block(FabricBlockSettings.copyOf(Blocks.END_STONE));
   public static final Block CRACKED_END_STONE = new Block(FabricBlockSettings.copyOf(Blocks.END_STONE));
   public static final Block CRACKED_BRICKS_END_STONE = new Block(FabricBlockSettings.copyOf(Blocks.END_STONE));
   public static final Block CUT_END_STONE = new Block(FabricBlockSettings.copyOf(Blocks.END_STONE));
   public static final Block DENT_END_STONE = new Block(FabricBlockSettings.copyOf(Blocks.END_STONE));
   public static final Block ENCASED_BRICKS_END_STONE = new Block(FabricBlockSettings.copyOf(Blocks.END_STONE));
   public static final Block FRENCH_END_STONE = new Block(FabricBlockSettings.copyOf(Blocks.END_STONE));
   public static final Block JELLYBEAN_END_STONE = new Block(FabricBlockSettings.copyOf(Blocks.END_STONE));
   public static final Block LARGE_TILE_END_STONE = new Block(FabricBlockSettings.copyOf(Blocks.END_STONE));
   public static final Block LAYER_END_STONE = new Block(FabricBlockSettings.copyOf(Blocks.END_STONE));
   public static final Block MOSAIC_END_STONE = new Block(FabricBlockSettings.copyOf(Blocks.END_STONE));
   public static final Block ORNATE_END_STONE = new Block(FabricBlockSettings.copyOf(Blocks.END_STONE));
   public static final Block PANEL_END_STONE = new Block(FabricBlockSettings.copyOf(Blocks.END_STONE));
   public static final PillarBlock PILLAR_END_STONE = new PillarBlock(FabricBlockSettings.copyOf(Blocks.END_STONE));
   public static final Block PRISM_END_STONE = new Block(FabricBlockSettings.copyOf(Blocks.END_STONE));
   public static final Block RAW_END_STONE = new Block(FabricBlockSettings.copyOf(Blocks.END_STONE));
   public static final Block ROAD_END_STONE = new Block(FabricBlockSettings.copyOf(Blocks.END_STONE));
   public static final Block SLANT_END_STONE = new Block(FabricBlockSettings.copyOf(Blocks.END_STONE));
   public static final Block SMALL_BRICKS_END_STONE = new Block(FabricBlockSettings.copyOf(Blocks.END_STONE));
   public static final Block SOFT_BRICKS_END_STONE = new Block(FabricBlockSettings.copyOf(Blocks.END_STONE));
   public static final Block SOLID_BRICKS_END_STONE = new Block(FabricBlockSettings.copyOf(Blocks.END_STONE));
   public static final Block TILES_MEDIUM_END_STONE = new Block(FabricBlockSettings.copyOf(Blocks.END_STONE));
   public static final Block TILES_SMALL_END_STONE = new Block(FabricBlockSettings.copyOf(Blocks.END_STONE));
   public static final Block TRIPLE_BRICKS_END_STONE = new Block(FabricBlockSettings.copyOf(Blocks.END_STONE));
   public static final PillarBlock TWIST_END_STONE = new PillarBlock(FabricBlockSettings.copyOf(Blocks.END_STONE));
   public static final Block WEAVER_END_STONE = new Block(FabricBlockSettings.copyOf(Blocks.END_STONE));
   public static final Block ZAG_END_STONE = new Block(FabricBlockSettings.copyOf(Blocks.END_STONE));
   public static final Block ARRAY_GLOWSTONE = new Block(FabricBlockSettings.copyOf(Blocks.GLOWSTONE));
   public static final Block BISMUTH_GLOWSTONE = new Block(FabricBlockSettings.copyOf(Blocks.GLOWSTONE));
   public static final Block BRAID_GLOWSTONE = new Block(FabricBlockSettings.copyOf(Blocks.GLOWSTONE));
   public static final Block CHAOTIC_MEDIUM_GLOWSTONE = new Block(FabricBlockSettings.copyOf(Blocks.GLOWSTONE));
   public static final Block CHAOTIC_SMALL_GLOWSTONE = new Block(FabricBlockSettings.copyOf(Blocks.GLOWSTONE));
   public static final Block CIRCULAR_GLOWSTONE = new Block(FabricBlockSettings.copyOf(Blocks.GLOWSTONE));
   public static final Block CRACKED_GLOWSTONE = new Block(FabricBlockSettings.copyOf(Blocks.GLOWSTONE));
   public static final Block CRACKED_BRICKS_GLOWSTONE = new Block(FabricBlockSettings.copyOf(Blocks.GLOWSTONE));
   public static final Block DENT_GLOWSTONE = new Block(FabricBlockSettings.copyOf(Blocks.GLOWSTONE));
   public static final Block ENCASED_BRICKS_GLOWSTONE = new Block(FabricBlockSettings.copyOf(Blocks.GLOWSTONE));
   public static final Block FRENCH_GLOWSTONE = new Block(FabricBlockSettings.copyOf(Blocks.GLOWSTONE));
   public static final Block JELLYBEAN_GLOWSTONE = new Block(FabricBlockSettings.copyOf(Blocks.GLOWSTONE));
   public static final Block LARGE_TILE_GLOWSTONE = new Block(FabricBlockSettings.copyOf(Blocks.GLOWSTONE));
   public static final Block LARGE_TILE_BISMUTH_GLOWSTONE = new Block(FabricBlockSettings.copyOf(Blocks.GLOWSTONE));
   public static final Block LAYER_GLOWSTONE = new Block(FabricBlockSettings.copyOf(Blocks.GLOWSTONE));
   public static final Block MOSAIC_GLOWSTONE = new Block(FabricBlockSettings.copyOf(Blocks.GLOWSTONE));
   public static final Block NEON_GLOWSTONE = new Block(FabricBlockSettings.copyOf(Blocks.GLOWSTONE));
   public static final Block NEON_PANEL_GLOWSTONE = new Block(FabricBlockSettings.copyOf(Blocks.GLOWSTONE));
   public static final Block ORNATE_GLOWSTONE = new Block(FabricBlockSettings.copyOf(Blocks.GLOWSTONE));
   public static final Block PANEL_GLOWSTONE = new Block(FabricBlockSettings.copyOf(Blocks.GLOWSTONE));
   public static final PillarBlock PILLAR_GLOWSTONE = new PillarBlock(FabricBlockSettings.copyOf(Blocks.GLOWSTONE));
   public static final Block PRISM_GLOWSTONE = new Block(FabricBlockSettings.copyOf(Blocks.GLOWSTONE));
   public static final Block ROAD_GLOWSTONE = new Block(FabricBlockSettings.copyOf(Blocks.GLOWSTONE));
   public static final Block SLANT_GLOWSTONE = new Block(FabricBlockSettings.copyOf(Blocks.GLOWSTONE));
   public static final Block SMALL_BRICKS_GLOWSTONE = new Block(FabricBlockSettings.copyOf(Blocks.GLOWSTONE));
   public static final Block SOFT_BRICKS_GLOWSTONE = new Block(FabricBlockSettings.copyOf(Blocks.GLOWSTONE));
   public static final Block SOLID_BRICKS_GLOWSTONE = new Block(FabricBlockSettings.copyOf(Blocks.GLOWSTONE));
   public static final Block TILES_MEDIUM_GLOWSTONE = new Block(FabricBlockSettings.copyOf(Blocks.GLOWSTONE));
   public static final Block TILES_MEDIUM_BISMUTH_GLOWSTONE = new Block(FabricBlockSettings.copyOf(Blocks.GLOWSTONE));
   public static final Block TILES_SMALL_GLOWSTONE = new Block(FabricBlockSettings.copyOf(Blocks.GLOWSTONE));
   public static final Block TRIPLE_BRICKS_GLOWSTONE = new Block(FabricBlockSettings.copyOf(Blocks.GLOWSTONE));
   public static final PillarBlock TWIST_GLOWSTONE = new PillarBlock(FabricBlockSettings.copyOf(Blocks.GLOWSTONE));
   public static final Block BRICK_GOLD_BLOCK = new Block(FabricBlockSettings.copyOf(Blocks.GOLD_BLOCK));
   public static final Block CART_GOLD_BLOCK = new Block(FabricBlockSettings.copyOf(Blocks.GOLD_BLOCK));
   public static final Block COIN_HEADS_GOLD_BLOCK = new Block(FabricBlockSettings.copyOf(Blocks.GOLD_BLOCK));
   public static final Block COIN_TAILS_GOLD_BLOCK = new Block(FabricBlockSettings.copyOf(Blocks.GOLD_BLOCK));
   public static final Block CRATE_DARK_GOLD_BLOCK = new Block(FabricBlockSettings.copyOf(Blocks.GOLD_BLOCK));
   public static final Block CRATE_LIGHT_GOLD_BLOCK = new Block(FabricBlockSettings.copyOf(Blocks.GOLD_BLOCK));
   public static final Block LARGEINGOT_GOLD_BLOCK = new Block(FabricBlockSettings.copyOf(Blocks.GOLD_BLOCK));
   public static final Block PLATES_GOLD_BLOCK = new Block(FabricBlockSettings.copyOf(Blocks.GOLD_BLOCK));
   public static final Block RIVETS_GOLD_BLOCK = new Block(FabricBlockSettings.copyOf(Blocks.GOLD_BLOCK));
   public static final Block SIMPLE_GOLD_BLOCK = new Block(FabricBlockSettings.copyOf(Blocks.GOLD_BLOCK));
   public static final Block SMALLINGOT_GOLD_BLOCK = new Block(FabricBlockSettings.copyOf(Blocks.GOLD_BLOCK));
   public static final Block SPACE_GOLD_BLOCK = new Block(FabricBlockSettings.copyOf(Blocks.GOLD_BLOCK));
   public static final Block SPACEBLACK_GOLD_BLOCK = new Block(FabricBlockSettings.copyOf(Blocks.GOLD_BLOCK));
   public static final Block STAR_GOLD_BLOCK = new Block(FabricBlockSettings.copyOf(Blocks.GOLD_BLOCK));
   public static final Block ARRAY_GRANITE = new Block(FabricBlockSettings.copyOf(Blocks.GRANITE));
   public static final Block BRAID_GRANITE = new Block(FabricBlockSettings.copyOf(Blocks.GRANITE));
   public static final Block CHAOTIC_BRICKS_GRANITE = new Block(FabricBlockSettings.copyOf(Blocks.GRANITE));
   public static final Block CHAOTIC_MEDIUM_GRANITE = new Block(FabricBlockSettings.copyOf(Blocks.GRANITE));
   public static final Block CHAOTIC_SMALL_GRANITE = new Block(FabricBlockSettings.copyOf(Blocks.GRANITE));
   public static final Block CIRCULAR_GRANITE = new Block(FabricBlockSettings.copyOf(Blocks.GRANITE));
   public static final Block CRACKED_GRANITE = new Block(FabricBlockSettings.copyOf(Blocks.GRANITE));
   public static final Block CRACKED_BRICKS_GRANITE = new Block(FabricBlockSettings.copyOf(Blocks.GRANITE));
   public static final Block CUT_GRANITE = new Block(FabricBlockSettings.copyOf(Blocks.GRANITE));
   public static final Block DENT_GRANITE = new Block(FabricBlockSettings.copyOf(Blocks.GRANITE));
   public static final Block ENCASED_BRICKS_GRANITE = new Block(FabricBlockSettings.copyOf(Blocks.GRANITE));
   public static final Block FRENCH_GRANITE = new Block(FabricBlockSettings.copyOf(Blocks.GRANITE));
   public static final Block JELLYBEAN_GRANITE = new Block(FabricBlockSettings.copyOf(Blocks.GRANITE));
   public static final Block LARGE_TILE_GRANITE = new Block(FabricBlockSettings.copyOf(Blocks.GRANITE));
   public static final Block LAYER_GRANITE = new Block(FabricBlockSettings.copyOf(Blocks.GRANITE));
   public static final Block MOSAIC_GRANITE = new Block(FabricBlockSettings.copyOf(Blocks.GRANITE));
   public static final Block ORNATE_GRANITE = new Block(FabricBlockSettings.copyOf(Blocks.GRANITE));
   public static final Block PANEL_GRANITE = new Block(FabricBlockSettings.copyOf(Blocks.GRANITE));
   public static final PillarBlock PILLAR_GRANITE = new PillarBlock(FabricBlockSettings.copyOf(Blocks.GRANITE));
   public static final Block PRISM_GRANITE = new Block(FabricBlockSettings.copyOf(Blocks.GRANITE));
   public static final Block RAW_GRANITE = new Block(FabricBlockSettings.copyOf(Blocks.GRANITE));
   public static final Block ROAD_GRANITE = new Block(FabricBlockSettings.copyOf(Blocks.GRANITE));
   public static final Block SLANT_GRANITE = new Block(FabricBlockSettings.copyOf(Blocks.GRANITE));
   public static final Block SMALL_BRICKS_GRANITE = new Block(FabricBlockSettings.copyOf(Blocks.GRANITE));
   public static final Block SOFT_BRICKS_GRANITE = new Block(FabricBlockSettings.copyOf(Blocks.GRANITE));
   public static final Block SOLID_BRICKS_GRANITE = new Block(FabricBlockSettings.copyOf(Blocks.GRANITE));
   public static final Block TILES_MEDIUM_GRANITE = new Block(FabricBlockSettings.copyOf(Blocks.GRANITE));
   public static final Block TILES_SMALL_GRANITE = new Block(FabricBlockSettings.copyOf(Blocks.GRANITE));
   public static final Block TRIPLE_BRICKS_GRANITE = new Block(FabricBlockSettings.copyOf(Blocks.GRANITE));
   public static final PillarBlock TWIST_GRANITE = new PillarBlock(FabricBlockSettings.copyOf(Blocks.GRANITE));
   public static final Block WEAVER_GRANITE = new Block(FabricBlockSettings.copyOf(Blocks.GRANITE));
   public static final Block ZAG_GRANITE = new Block(FabricBlockSettings.copyOf(Blocks.GRANITE));
   public static final Block BRICK_IRON_BLOCK = new Block(FabricBlockSettings.copyOf(Blocks.IRON_BLOCK));
   public static final Block COIN_HEADS_IRON_BLOCK = new Block(FabricBlockSettings.copyOf(Blocks.IRON_BLOCK));
   public static final Block COIN_TAILS_IRON_BLOCK = new Block(FabricBlockSettings.copyOf(Blocks.IRON_BLOCK));
   public static final Block CRATE_DARK_IRON_BLOCK = new Block(FabricBlockSettings.copyOf(Blocks.IRON_BLOCK));
   public static final Block CRATE_LIGHT_IRON_BLOCK = new Block(FabricBlockSettings.copyOf(Blocks.IRON_BLOCK));
   public static final Block GEARS_IRON_BLOCK = new Block(FabricBlockSettings.copyOf(Blocks.IRON_BLOCK));
   public static final Block LARGEINGOT_IRON_BLOCK = new Block(FabricBlockSettings.copyOf(Blocks.IRON_BLOCK));
   public static final Block MOON_IRON_BLOCK = new Block(FabricBlockSettings.copyOf(Blocks.IRON_BLOCK));
   public static final Block PLATES_IRON_BLOCK = new Block(FabricBlockSettings.copyOf(Blocks.IRON_BLOCK));
   public static final Block RIVETS_IRON_BLOCK = new Block(FabricBlockSettings.copyOf(Blocks.IRON_BLOCK));
   public static final Block SIMPLE_IRON_BLOCK = new Block(FabricBlockSettings.copyOf(Blocks.IRON_BLOCK));
   public static final Block SMALLINGOT_IRON_BLOCK = new Block(FabricBlockSettings.copyOf(Blocks.IRON_BLOCK));
   public static final Block SPACE_IRON_BLOCK = new Block(FabricBlockSettings.copyOf(Blocks.IRON_BLOCK));
   public static final Block SPACEBLACK_IRON_BLOCK = new Block(FabricBlockSettings.copyOf(Blocks.IRON_BLOCK));
   public static final Block VENTS_IRON_BLOCK = new Block(FabricBlockSettings.copyOf(Blocks.IRON_BLOCK));
   public static final Block CHUNKY_LAPIS_BLOCK = new Block(FabricBlockSettings.copyOf(Blocks.LAPIS_BLOCK));
   public static final Block LARGE_TILE_LAPIS_BLOCK = new Block(FabricBlockSettings.copyOf(Blocks.LAPIS_BLOCK));
   public static final Block MASONRY_LAPIS_BLOCK = new Block(FabricBlockSettings.copyOf(Blocks.LAPIS_BLOCK));
   public static final Block ORNATE_LAPIS_BLOCK = new Block(FabricBlockSettings.copyOf(Blocks.LAPIS_BLOCK));
   public static final Block ORNATELAYER_LAPIS_BLOCK = new Block(FabricBlockSettings.copyOf(Blocks.LAPIS_BLOCK));
   public static final Block PANEL_LAPIS_BLOCK = new Block(FabricBlockSettings.copyOf(Blocks.LAPIS_BLOCK));
   public static final Block PANELCLASSIC_LAPIS_BLOCK = new Block(FabricBlockSettings.copyOf(Blocks.LAPIS_BLOCK));
   public static final Block SMOOTH_LAPIS_BLOCK = new Block(FabricBlockSettings.copyOf(Blocks.LAPIS_BLOCK));
   public static final Block ZELDA_LAPIS_BLOCK = new Block(FabricBlockSettings.copyOf(Blocks.LAPIS_BLOCK));
   public static final Block MOSAIC_NETHER_BRICK = new Block(FabricBlockSettings.copyOf(Blocks.NETHER_BRICKS));
   public static final PillarBlock PILLAR_NETHER_BRICK = new PillarBlock(FabricBlockSettings.copyOf(Blocks.NETHER_BRICKS));
   public static final Block SLANT_NETHER_BRICK = new Block(FabricBlockSettings.copyOf(Blocks.NETHER_BRICKS));
   public static final Block ARRAY_PURPUR = new Block(FabricBlockSettings.copyOf(Blocks.PURPUR_BLOCK));
   public static final Block BRAID_PURPUR = new Block(FabricBlockSettings.copyOf(Blocks.PURPUR_BLOCK));
   public static final Block CHAOTIC_BRICKS_PURPUR = new Block(FabricBlockSettings.copyOf(Blocks.PURPUR_BLOCK));
   public static final Block CHAOTIC_MEDIUM_PURPUR = new Block(FabricBlockSettings.copyOf(Blocks.PURPUR_BLOCK));
   public static final Block CHAOTIC_SMALL_PURPUR = new Block(FabricBlockSettings.copyOf(Blocks.PURPUR_BLOCK));
   public static final Block CIRCULAR_PURPUR = new Block(FabricBlockSettings.copyOf(Blocks.PURPUR_BLOCK));
   public static final Block CRACKED_PURPUR = new Block(FabricBlockSettings.copyOf(Blocks.PURPUR_BLOCK));
   public static final Block CRACKED_BRICKS_PURPUR = new Block(FabricBlockSettings.copyOf(Blocks.PURPUR_BLOCK));
   public static final Block CUT_PURPUR = new Block(FabricBlockSettings.copyOf(Blocks.PURPUR_BLOCK));
   public static final Block DENT_PURPUR = new Block(FabricBlockSettings.copyOf(Blocks.PURPUR_BLOCK));
   public static final Block ENCASED_BRICKS_PURPUR = new Block(FabricBlockSettings.copyOf(Blocks.PURPUR_BLOCK));
   public static final Block FRENCH_PURPUR = new Block(FabricBlockSettings.copyOf(Blocks.PURPUR_BLOCK));
   public static final Block JELLYBEAN_PURPUR = new Block(FabricBlockSettings.copyOf(Blocks.PURPUR_BLOCK));
   public static final Block LARGE_TILE_PURPUR = new Block(FabricBlockSettings.copyOf(Blocks.PURPUR_BLOCK));
   public static final Block LAYER_PURPUR = new Block(FabricBlockSettings.copyOf(Blocks.PURPUR_BLOCK));
   public static final Block MOSAIC_PURPUR = new Block(FabricBlockSettings.copyOf(Blocks.PURPUR_BLOCK));
   public static final Block ORNATE_PURPUR = new Block(FabricBlockSettings.copyOf(Blocks.PURPUR_BLOCK));
   public static final Block PANEL_PURPUR = new Block(FabricBlockSettings.copyOf(Blocks.PURPUR_BLOCK));
   public static final PillarBlock PILLAR_PURPUR = new PillarBlock(FabricBlockSettings.copyOf(Blocks.PURPUR_BLOCK));
   public static final Block PRISM_PURPUR = new Block(FabricBlockSettings.copyOf(Blocks.PURPUR_BLOCK));
   public static final Block RAW_PURPUR = new Block(FabricBlockSettings.copyOf(Blocks.PURPUR_BLOCK));
   public static final Block ROAD_PURPUR = new Block(FabricBlockSettings.copyOf(Blocks.PURPUR_BLOCK));
   public static final Block SLANT_PURPUR = new Block(FabricBlockSettings.copyOf(Blocks.PURPUR_BLOCK));
   public static final Block SMALL_BRICKS_PURPUR = new Block(FabricBlockSettings.copyOf(Blocks.PURPUR_BLOCK));
   public static final Block SOFT_BRICKS_PURPUR = new Block(FabricBlockSettings.copyOf(Blocks.PURPUR_BLOCK));
   public static final Block SOLID_BRICKS_PURPUR = new Block(FabricBlockSettings.copyOf(Blocks.PURPUR_BLOCK));
   public static final Block TILES_MEDIUM_PURPUR = new Block(FabricBlockSettings.copyOf(Blocks.PURPUR_BLOCK));
   public static final Block TILES_SMALL_PURPUR = new Block(FabricBlockSettings.copyOf(Blocks.PURPUR_BLOCK));
   public static final Block TRIPLE_BRICKS_PURPUR = new Block(FabricBlockSettings.copyOf(Blocks.PURPUR_BLOCK));
   public static final PillarBlock TWIST_PURPUR = new PillarBlock(FabricBlockSettings.copyOf(Blocks.PURPUR_BLOCK));
   public static final Block WEAVER_PURPUR = new Block(FabricBlockSettings.copyOf(Blocks.PURPUR_BLOCK));
   public static final Block ZAG_PURPUR = new Block(FabricBlockSettings.copyOf(Blocks.PURPUR_BLOCK));
   public static final Block ARRAY_QUARTZ = new Block(FabricBlockSettings.copyOf(Blocks.QUARTZ_BLOCK));
   public static final Block BRAID_QUARTZ = new Block(FabricBlockSettings.copyOf(Blocks.QUARTZ_BLOCK));
   public static final Block CHAOTIC_BRICKS_QUARTZ = new Block(FabricBlockSettings.copyOf(Blocks.QUARTZ_BLOCK));
   public static final Block CHAOTIC_MEDIUM_QUARTZ = new Block(FabricBlockSettings.copyOf(Blocks.QUARTZ_BLOCK));
   public static final Block CHAOTIC_SMALL_QUARTZ = new Block(FabricBlockSettings.copyOf(Blocks.QUARTZ_BLOCK));
   public static final Block CIRCULAR_QUARTZ = new Block(FabricBlockSettings.copyOf(Blocks.QUARTZ_BLOCK));
   public static final Block CRACKED_QUARTZ = new Block(FabricBlockSettings.copyOf(Blocks.QUARTZ_BLOCK));
   public static final Block CRACKED_BRICKS_QUARTZ = new Block(FabricBlockSettings.copyOf(Blocks.QUARTZ_BLOCK));
   public static final Block CUT_QUARTZ = new Block(FabricBlockSettings.copyOf(Blocks.QUARTZ_BLOCK));
   public static final Block DENT_QUARTZ = new Block(FabricBlockSettings.copyOf(Blocks.QUARTZ_BLOCK));
   public static final Block ENCASED_BRICKS_QUARTZ = new Block(FabricBlockSettings.copyOf(Blocks.QUARTZ_BLOCK));
   public static final Block FRENCH_QUARTZ = new Block(FabricBlockSettings.copyOf(Blocks.QUARTZ_BLOCK));
   public static final Block JELLYBEAN_QUARTZ = new Block(FabricBlockSettings.copyOf(Blocks.QUARTZ_BLOCK));
   public static final Block LARGE_TILE_QUARTZ = new Block(FabricBlockSettings.copyOf(Blocks.QUARTZ_BLOCK));
   public static final Block LAYER_QUARTZ = new Block(FabricBlockSettings.copyOf(Blocks.QUARTZ_BLOCK));
   public static final Block MOSAIC_QUARTZ = new Block(FabricBlockSettings.copyOf(Blocks.QUARTZ_BLOCK));
   public static final Block ORNATE_QUARTZ = new Block(FabricBlockSettings.copyOf(Blocks.QUARTZ_BLOCK));
   public static final Block PANEL_QUARTZ = new Block(FabricBlockSettings.copyOf(Blocks.QUARTZ_BLOCK));
   public static final PillarBlock PILLAR_QUARTZ = new PillarBlock(FabricBlockSettings.copyOf(Blocks.QUARTZ_BLOCK));
   public static final Block PRISM_QUARTZ = new Block(FabricBlockSettings.copyOf(Blocks.QUARTZ_BLOCK));
   public static final Block RAW_QUARTZ = new Block(FabricBlockSettings.copyOf(Blocks.QUARTZ_BLOCK));
   public static final Block ROAD_QUARTZ = new Block(FabricBlockSettings.copyOf(Blocks.QUARTZ_BLOCK));
   public static final Block SLANT_QUARTZ = new Block(FabricBlockSettings.copyOf(Blocks.QUARTZ_BLOCK));
   public static final Block SMALL_BRICKS_QUARTZ = new Block(FabricBlockSettings.copyOf(Blocks.QUARTZ_BLOCK));
   public static final Block SOFT_BRICKS_QUARTZ = new Block(FabricBlockSettings.copyOf(Blocks.QUARTZ_BLOCK));
   public static final Block SOLID_BRICKS_QUARTZ = new Block(FabricBlockSettings.copyOf(Blocks.QUARTZ_BLOCK));
   public static final Block TILES_MEDIUM_QUARTZ = new Block(FabricBlockSettings.copyOf(Blocks.QUARTZ_BLOCK));
   public static final Block TILES_SMALL_QUARTZ = new Block(FabricBlockSettings.copyOf(Blocks.QUARTZ_BLOCK));
   public static final Block TRIPLE_BRICKS_QUARTZ = new Block(FabricBlockSettings.copyOf(Blocks.QUARTZ_BLOCK));
   public static final PillarBlock TWIST_QUARTZ = new PillarBlock(FabricBlockSettings.copyOf(Blocks.QUARTZ_BLOCK));
   public static final Block WEAVER_QUARTZ = new Block(FabricBlockSettings.copyOf(Blocks.QUARTZ_BLOCK));
   public static final Block ZAG_QUARTZ = new Block(FabricBlockSettings.copyOf(Blocks.QUARTZ_BLOCK));
   public static final Block ARRAY_RED_SANDSTONE = new Block(FabricBlockSettings.copyOf(Blocks.RED_SANDSTONE));
   public static final Block BEVEL_SKELETON_RED_SANDSTONE = new Block(FabricBlockSettings.copyOf(Blocks.RED_SANDSTONE));
   public static final Block BRAID_RED_SANDSTONE = new Block(FabricBlockSettings.copyOf(Blocks.RED_SANDSTONE));
   public static final Block CHAOTIC_BRICKS_RED_SANDSTONE = new Block(FabricBlockSettings.copyOf(Blocks.RED_SANDSTONE));
   public static final Block CHAOTIC_MEDIUM_RED_SANDSTONE = new Block(FabricBlockSettings.copyOf(Blocks.RED_SANDSTONE));
   public static final Block CHAOTIC_SMALL_RED_SANDSTONE = new Block(FabricBlockSettings.copyOf(Blocks.RED_SANDSTONE));
   public static final Block CIRCULAR_RED_SANDSTONE = new Block(FabricBlockSettings.copyOf(Blocks.RED_SANDSTONE));
   public static final Block CRACKED_RED_SANDSTONE = new Block(FabricBlockSettings.copyOf(Blocks.RED_SANDSTONE));
   public static final Block CRACKED_BRICKS_RED_SANDSTONE = new Block(FabricBlockSettings.copyOf(Blocks.RED_SANDSTONE));
   public static final Block CUT_RED_SANDSTONE = new Block(FabricBlockSettings.copyOf(Blocks.RED_SANDSTONE));
   public static final Block DENT_RED_SANDSTONE = new Block(FabricBlockSettings.copyOf(Blocks.RED_SANDSTONE));
   public static final Block ENCASED_BRICKS_RED_SANDSTONE = new Block(FabricBlockSettings.copyOf(Blocks.RED_SANDSTONE));
   public static final Block FRENCH_RED_SANDSTONE = new Block(FabricBlockSettings.copyOf(Blocks.RED_SANDSTONE));
   public static final Block GLYPHS_RED_SANDSTONE = new Block(FabricBlockSettings.copyOf(Blocks.RED_SANDSTONE));
   public static final Block JELLYBEAN_RED_SANDSTONE = new Block(FabricBlockSettings.copyOf(Blocks.RED_SANDSTONE));
   public static final Block LARGE_TILE_RED_SANDSTONE = new Block(FabricBlockSettings.copyOf(Blocks.RED_SANDSTONE));
   public static final Block LAYER_RED_SANDSTONE = new Block(FabricBlockSettings.copyOf(Blocks.RED_SANDSTONE));
   public static final Block MOSAIC_RED_SANDSTONE = new Block(FabricBlockSettings.copyOf(Blocks.RED_SANDSTONE));
   public static final Block ORNATE_RED_SANDSTONE = new Block(FabricBlockSettings.copyOf(Blocks.RED_SANDSTONE));
   public static final Block PANEL_RED_SANDSTONE = new Block(FabricBlockSettings.copyOf(Blocks.RED_SANDSTONE));
   public static final PillarBlock PILLAR_RED_SANDSTONE = new PillarBlock(FabricBlockSettings.copyOf(Blocks.RED_SANDSTONE));
   public static final Block PRISM_RED_SANDSTONE = new Block(FabricBlockSettings.copyOf(Blocks.RED_SANDSTONE));
   public static final Block RAW_RED_SANDSTONE = new Block(FabricBlockSettings.copyOf(Blocks.RED_SANDSTONE));
   public static final Block ROAD_RED_SANDSTONE = new Block(FabricBlockSettings.copyOf(Blocks.RED_SANDSTONE));
   public static final Block SLANT_RED_SANDSTONE = new Block(FabricBlockSettings.copyOf(Blocks.RED_SANDSTONE));
   public static final Block SMALL_RED_SANDSTONE = new Block(FabricBlockSettings.copyOf(Blocks.RED_SANDSTONE));
   public static final Block SMALL_BRICKS_RED_SANDSTONE = new Block(FabricBlockSettings.copyOf(Blocks.RED_SANDSTONE));
   public static final Block SOFT_BRICKS_RED_SANDSTONE = new Block(FabricBlockSettings.copyOf(Blocks.RED_SANDSTONE));
   public static final Block SOLID_BRICKS_RED_SANDSTONE = new Block(FabricBlockSettings.copyOf(Blocks.RED_SANDSTONE));
   public static final Block TILES_MEDIUM_RED_SANDSTONE = new Block(FabricBlockSettings.copyOf(Blocks.RED_SANDSTONE));
   public static final Block TILES_SMALL_RED_SANDSTONE = new Block(FabricBlockSettings.copyOf(Blocks.RED_SANDSTONE));
   public static final Block TRIPLE_BRICKS_RED_SANDSTONE = new Block(FabricBlockSettings.copyOf(Blocks.RED_SANDSTONE));
   public static final PillarBlock TWIST_RED_SANDSTONE = new PillarBlock(FabricBlockSettings.copyOf(Blocks.RED_SANDSTONE));
   public static final Block WEAVER_RED_SANDSTONE = new Block(FabricBlockSettings.copyOf(Blocks.RED_SANDSTONE));
   public static final Block ZAG_RED_SANDSTONE = new Block(FabricBlockSettings.copyOf(Blocks.RED_SANDSTONE));
   public static final RedstoneBlock ARRAY_REDSTONE_BLOCK = new RedstoneBlock(FabricBlockSettings.copyOf(Blocks.REDSTONE_BLOCK));
   public static final RedstoneBlock BRAID_REDSTONE_BLOCK = new RedstoneBlock(FabricBlockSettings.copyOf(Blocks.REDSTONE_BLOCK));
   public static final RedstoneBlock CHAOTIC_MEDIUM_REDSTONE_BLOCK = new RedstoneBlock(FabricBlockSettings.copyOf(Blocks.REDSTONE_BLOCK));
   public static final RedstoneBlock CHAOTIC_SMALL_REDSTONE_BLOCK = new RedstoneBlock(FabricBlockSettings.copyOf(Blocks.REDSTONE_BLOCK));
   public static final RedstoneBlock CIRCULAR_REDSTONE_BLOCK = new RedstoneBlock(FabricBlockSettings.copyOf(Blocks.REDSTONE_BLOCK));
   public static final RedstoneBlock CRACKED_REDSTONE_BLOCK = new RedstoneBlock(FabricBlockSettings.copyOf(Blocks.REDSTONE_BLOCK));
   public static final RedstoneBlock CRACKED_BRICKS_REDSTONE_BLOCK = new RedstoneBlock(FabricBlockSettings.copyOf(Blocks.REDSTONE_BLOCK));
   public static final RedstoneBlock DENT_REDSTONE_BLOCK = new RedstoneBlock(FabricBlockSettings.copyOf(Blocks.REDSTONE_BLOCK));
   public static final RedstoneBlock ENCASED_BRICKS_REDSTONE_BLOCK = new RedstoneBlock(FabricBlockSettings.copyOf(Blocks.REDSTONE_BLOCK));
   public static final RedstoneBlock FRENCH_REDSTONE_BLOCK = new RedstoneBlock(FabricBlockSettings.copyOf(Blocks.REDSTONE_BLOCK));
   public static final RedstoneBlock JELLYBEAN_REDSTONE_BLOCK = new RedstoneBlock(FabricBlockSettings.copyOf(Blocks.REDSTONE_BLOCK));
   public static final RedstoneBlock LARGE_TILE_REDSTONE_BLOCK = new RedstoneBlock(FabricBlockSettings.copyOf(Blocks.REDSTONE_BLOCK));
   public static final RedstoneBlock LAYER_REDSTONE_BLOCK = new RedstoneBlock(FabricBlockSettings.copyOf(Blocks.REDSTONE_BLOCK));
   public static final RedstoneBlock MOSAIC_REDSTONE_BLOCK = new RedstoneBlock(FabricBlockSettings.copyOf(Blocks.REDSTONE_BLOCK));
   public static final RedstoneBlock ORNATE_REDSTONE_BLOCK = new RedstoneBlock(FabricBlockSettings.copyOf(Blocks.REDSTONE_BLOCK));
   public static final RedstoneBlock PANEL_REDSTONE_BLOCK = new RedstoneBlock(FabricBlockSettings.copyOf(Blocks.REDSTONE_BLOCK));
   public static final RedstonePillarBlock PILLAR_REDSTONE_BLOCK = new RedstonePillarBlock(FabricBlockSettings.copyOf(Blocks.REDSTONE_BLOCK));
   public static final RedstoneBlock PRISM_REDSTONE_BLOCK = new RedstoneBlock(FabricBlockSettings.copyOf(Blocks.REDSTONE_BLOCK));
   public static final RedstoneBlock ROAD_REDSTONE_BLOCK = new RedstoneBlock(FabricBlockSettings.copyOf(Blocks.REDSTONE_BLOCK));
   public static final RedstoneBlock SLANT_REDSTONE_BLOCK = new RedstoneBlock(FabricBlockSettings.copyOf(Blocks.REDSTONE_BLOCK));
   public static final RedstoneBlock SMALL_BRICKS_REDSTONE_BLOCK = new RedstoneBlock(FabricBlockSettings.copyOf(Blocks.REDSTONE_BLOCK));
   public static final RedstoneBlock SOFT_BRICKS_REDSTONE_BLOCK = new RedstoneBlock(FabricBlockSettings.copyOf(Blocks.REDSTONE_BLOCK));
   public static final RedstoneBlock SOLID_BRICKS_REDSTONE_BLOCK = new RedstoneBlock(FabricBlockSettings.copyOf(Blocks.REDSTONE_BLOCK));
   public static final RedstoneBlock TILES_MEDIUM_REDSTONE_BLOCK = new RedstoneBlock(FabricBlockSettings.copyOf(Blocks.REDSTONE_BLOCK));
   public static final RedstoneBlock TILES_SMALL_REDSTONE_BLOCK = new RedstoneBlock(FabricBlockSettings.copyOf(Blocks.REDSTONE_BLOCK));
   public static final RedstoneBlock TRIPLE_BRICKS_REDSTONE_BLOCK = new RedstoneBlock(FabricBlockSettings.copyOf(Blocks.REDSTONE_BLOCK));
   public static final RedstonePillarBlock TWIST_REDSTONE_BLOCK = new RedstonePillarBlock(FabricBlockSettings.copyOf(Blocks.REDSTONE_BLOCK));
   public static final Block ARRAY_SANDSTONE = new Block(FabricBlockSettings.copyOf(Blocks.SANDSTONE));
   public static final Block BEVEL_CREEPER_SANDSTONE = new Block(FabricBlockSettings.copyOf(Blocks.SANDSTONE));
   public static final Block BRAID_SANDSTONE = new Block(FabricBlockSettings.copyOf(Blocks.SANDSTONE));
   public static final Block CHAOTIC_BRICKS_SANDSTONE = new Block(FabricBlockSettings.copyOf(Blocks.SANDSTONE));
   public static final Block CHAOTIC_MEDIUM_SANDSTONE = new Block(FabricBlockSettings.copyOf(Blocks.SANDSTONE));
   public static final Block CHAOTIC_SMALL_SANDSTONE = new Block(FabricBlockSettings.copyOf(Blocks.SANDSTONE));
   public static final Block CIRCULAR_SANDSTONE = new Block(FabricBlockSettings.copyOf(Blocks.SANDSTONE));
   public static final Block CRACKED_SANDSTONE = new Block(FabricBlockSettings.copyOf(Blocks.SANDSTONE));
   public static final Block CRACKED_BRICKS_SANDSTONE = new Block(FabricBlockSettings.copyOf(Blocks.SANDSTONE));
   public static final Block CUT_SANDSTONE = new Block(FabricBlockSettings.copyOf(Blocks.SANDSTONE));
   public static final Block DENT_SANDSTONE = new Block(FabricBlockSettings.copyOf(Blocks.SANDSTONE));
   public static final Block ENCASED_BRICKS_SANDSTONE = new Block(FabricBlockSettings.copyOf(Blocks.SANDSTONE));
   public static final Block FRENCH_SANDSTONE = new Block(FabricBlockSettings.copyOf(Blocks.SANDSTONE));
   public static final Block GLYPHS_SANDSTONE = new Block(FabricBlockSettings.copyOf(Blocks.SANDSTONE));
   public static final Block JELLYBEAN_SANDSTONE = new Block(FabricBlockSettings.copyOf(Blocks.SANDSTONE));
   public static final Block LARGE_TILE_SANDSTONE = new Block(FabricBlockSettings.copyOf(Blocks.SANDSTONE));
   public static final Block LAYER_SANDSTONE = new Block(FabricBlockSettings.copyOf(Blocks.SANDSTONE));
   public static final Block MOSAIC_SANDSTONE = new Block(FabricBlockSettings.copyOf(Blocks.SANDSTONE));
   public static final Block ORNATE_SANDSTONE = new Block(FabricBlockSettings.copyOf(Blocks.SANDSTONE));
   public static final Block PANEL_SANDSTONE = new Block(FabricBlockSettings.copyOf(Blocks.SANDSTONE));
   public static final PillarBlock PILLAR_SANDSTONE = new PillarBlock(FabricBlockSettings.copyOf(Blocks.SANDSTONE));
   public static final Block PRISM_SANDSTONE = new Block(FabricBlockSettings.copyOf(Blocks.SANDSTONE));
   public static final Block RAW_SANDSTONE = new Block(FabricBlockSettings.copyOf(Blocks.SANDSTONE));
   public static final Block ROAD_SANDSTONE = new Block(FabricBlockSettings.copyOf(Blocks.SANDSTONE));
   public static final Block SLANT_SANDSTONE = new Block(FabricBlockSettings.copyOf(Blocks.SANDSTONE));
   public static final Block SMALL_SANDSTONE = new Block(FabricBlockSettings.copyOf(Blocks.SANDSTONE));
   public static final Block SMALL_BRICKS_SANDSTONE = new Block(FabricBlockSettings.copyOf(Blocks.SANDSTONE));
   public static final Block SOFT_BRICKS_SANDSTONE = new Block(FabricBlockSettings.copyOf(Blocks.SANDSTONE));
   public static final Block SOLID_BRICKS_SANDSTONE = new Block(FabricBlockSettings.copyOf(Blocks.SANDSTONE));
   public static final Block TILES_MEDIUM_SANDSTONE = new Block(FabricBlockSettings.copyOf(Blocks.SANDSTONE));
   public static final Block TILES_SMALL_SANDSTONE = new Block(FabricBlockSettings.copyOf(Blocks.SANDSTONE));
   public static final Block TRIPLE_BRICKS_SANDSTONE = new Block(FabricBlockSettings.copyOf(Blocks.SANDSTONE));
   public static final PillarBlock TWIST_SANDSTONE = new PillarBlock(FabricBlockSettings.copyOf(Blocks.SANDSTONE));
   public static final Block WEAVER_SANDSTONE = new Block(FabricBlockSettings.copyOf(Blocks.SANDSTONE));
   public static final Block ZAG_SANDSTONE = new Block(FabricBlockSettings.copyOf(Blocks.SANDSTONE));
   public static final Block ARRAY_STONE = new Block(FabricBlockSettings.copyOf(Blocks.STONE));
   public static final Block BRAID_STONE = new Block(FabricBlockSettings.copyOf(Blocks.STONE));
   public static final Block CHAOTIC_BRICKS_STONE = new Block(FabricBlockSettings.copyOf(Blocks.STONE));
   public static final Block CHAOTIC_MEDIUM_STONE = new Block(FabricBlockSettings.copyOf(Blocks.STONE));
   public static final Block CHAOTIC_SMALL_STONE = new Block(FabricBlockSettings.copyOf(Blocks.STONE));
   public static final Block CIRCULAR_STONE = new Block(FabricBlockSettings.copyOf(Blocks.STONE));
   public static final Block CRACKED_STONE = new Block(FabricBlockSettings.copyOf(Blocks.STONE));
   public static final Block CRACKED_BRICKS_STONE = new Block(FabricBlockSettings.copyOf(Blocks.STONE));
   public static final Block CUT_STONE = new Block(FabricBlockSettings.copyOf(Blocks.STONE));
   public static final Block DENT_STONE = new Block(FabricBlockSettings.copyOf(Blocks.STONE));
   public static final Block ENCASED_BRICKS_STONE = new Block(FabricBlockSettings.copyOf(Blocks.STONE));
   public static final Block FRENCH_STONE = new Block(FabricBlockSettings.copyOf(Blocks.STONE));
   public static final Block JELLYBEAN_STONE = new Block(FabricBlockSettings.copyOf(Blocks.STONE));
   public static final Block LARGE_TILE_STONE = new Block(FabricBlockSettings.copyOf(Blocks.STONE));
   public static final Block LARGEORNATE_STONE = new Block(FabricBlockSettings.copyOf(Blocks.STONE));
   public static final Block LAYER_STONE = new Block(FabricBlockSettings.copyOf(Blocks.STONE));
   public static final Block MOSAIC_STONE = new Block(FabricBlockSettings.copyOf(Blocks.STONE));
   public static final Block ORNATE_STONE = new Block(FabricBlockSettings.copyOf(Blocks.STONE));
   public static final Block PANEL_STONE = new Block(FabricBlockSettings.copyOf(Blocks.STONE));
   public static final PillarBlock PILLAR_STONE = new PillarBlock(FabricBlockSettings.copyOf(Blocks.STONE));
   public static final Block POISON_STONE = new Block(FabricBlockSettings.copyOf(Blocks.STONE));
   public static final Block PRISM_STONE = new Block(FabricBlockSettings.copyOf(Blocks.STONE));
   public static final Block RAW_STONE = new Block(FabricBlockSettings.copyOf(Blocks.STONE));
   public static final Block ROAD_STONE = new Block(FabricBlockSettings.copyOf(Blocks.STONE));
   public static final Block SLANT_STONE = new Block(FabricBlockSettings.copyOf(Blocks.STONE));
   public static final Block SMALL_BRICKS_STONE = new Block(FabricBlockSettings.copyOf(Blocks.STONE));
   public static final Block SOFT_BRICKS_STONE = new Block(FabricBlockSettings.copyOf(Blocks.STONE));
   public static final Block SOLID_BRICKS_STONE = new Block(FabricBlockSettings.copyOf(Blocks.STONE));
   public static final Block SUNKEN_STONE = new Block(FabricBlockSettings.copyOf(Blocks.STONE));
   public static final Block TILES_MEDIUM_STONE = new Block(FabricBlockSettings.copyOf(Blocks.STONE));
   public static final Block TILES_SMALL_STONE = new Block(FabricBlockSettings.copyOf(Blocks.STONE));
   public static final Block TRIPLE_BRICKS_STONE = new Block(FabricBlockSettings.copyOf(Blocks.STONE));
   public static final PillarBlock TWIST_STONE = new PillarBlock(FabricBlockSettings.copyOf(Blocks.STONE));
   public static final Block WEAVER_STONE = new Block(FabricBlockSettings.copyOf(Blocks.STONE));
   public static final Block ZAG_STONE = new Block(FabricBlockSettings.copyOf(Blocks.STONE));

    public static void Register()
    {
        Reg("andesite", "array/andesite", ARRAY_ANDESITE);
        Reg("andesite", "braid/andesite", BRAID_ANDESITE);
        Reg("andesite", "chaotic_bricks/andesite", CHAOTIC_BRICKS_ANDESITE);
        Reg("andesite", "chaotic_medium/andesite", CHAOTIC_MEDIUM_ANDESITE);
        Reg("andesite", "chaotic_small/andesite", CHAOTIC_SMALL_ANDESITE);
        Reg("andesite", "circular/andesite", CIRCULAR_ANDESITE);
        Reg("andesite", "cracked/andesite", CRACKED_ANDESITE);
        Reg("andesite", "cracked_bricks/andesite", CRACKED_BRICKS_ANDESITE);
        Reg("andesite", "cut/andesite", CUT_ANDESITE);
        Reg("andesite", "dent/andesite", DENT_ANDESITE);
        Reg("andesite", "encased_bricks/andesite", ENCASED_BRICKS_ANDESITE);
        Reg("andesite", "french/andesite", FRENCH_ANDESITE);
        Reg("andesite", "jellybean/andesite", JELLYBEAN_ANDESITE);
        Reg("andesite", "large_tile/andesite", LARGE_TILE_ANDESITE);
        Reg("andesite", "layer/andesite", LAYER_ANDESITE);
        Reg("andesite", "mosaic/andesite", MOSAIC_ANDESITE);
        Reg("andesite", "ornate/andesite", ORNATE_ANDESITE);
        Reg("andesite", "panel/andesite", PANEL_ANDESITE);
        Reg("andesite", "pillar/andesite", PILLAR_ANDESITE);
        Reg("andesite", "prism/andesite", PRISM_ANDESITE);
        Reg("andesite", "raw/andesite", RAW_ANDESITE);
        Reg("andesite", "road/andesite", ROAD_ANDESITE);
        Reg("andesite", "slant/andesite", SLANT_ANDESITE);
        Reg("andesite", "small_bricks/andesite", SMALL_BRICKS_ANDESITE);
        Reg("andesite", "soft_bricks/andesite", SOFT_BRICKS_ANDESITE);
        Reg("andesite", "solid_bricks/andesite", SOLID_BRICKS_ANDESITE);
        Reg("andesite", "tiles_medium/andesite", TILES_MEDIUM_ANDESITE);
        Reg("andesite", "tiles_small/andesite", TILES_SMALL_ANDESITE);
        Reg("andesite", "triple_bricks/andesite", TRIPLE_BRICKS_ANDESITE);
        Reg("andesite", "twist/andesite", TWIST_ANDESITE);
        Reg("andesite", "weaver/andesite", WEAVER_ANDESITE);
        Reg("andesite", "zag/andesite", ZAG_ANDESITE);
        Reg("blackstone", "pillar/blackstone", PILLAR_BLACKSTONE);
        Reg("bricks", "array/bricks", ARRAY_BRICKS);
        Reg("bricks", "braid/bricks", BRAID_BRICKS);
        Reg("bricks", "chaotic_bricks/bricks", CHAOTIC_BRICKS_BRICKS);
        Reg("bricks", "chaotic_medium/bricks", CHAOTIC_MEDIUM_BRICKS);
        Reg("bricks", "chaotic_small/bricks", CHAOTIC_SMALL_BRICKS);
        Reg("bricks", "circular/bricks", CIRCULAR_BRICKS);
        Reg("bricks", "cracked/bricks", CRACKED_BRICKS);
        Reg("bricks", "cracked_bricks/bricks", CRACKED_BRICKS_BRICKS);
        Reg("bricks", "cut/bricks", CUT_BRICKS);
        Reg("bricks", "dent/bricks", DENT_BRICKS);
        Reg("bricks", "encased_bricks/bricks", ENCASED_BRICKS_BRICKS);
        Reg("bricks", "french/bricks", FRENCH_BRICKS);
        Reg("bricks", "jellybean/bricks", JELLYBEAN_BRICKS);
        Reg("bricks", "large_tile/bricks", LARGE_TILE_BRICKS);
        Reg("bricks", "layer/bricks", LAYER_BRICKS);
        Reg("bricks", "mosaic/bricks", MOSAIC_BRICKS);
        Reg("bricks", "ornate/bricks", ORNATE_BRICKS);
        Reg("bricks", "panel/bricks", PANEL_BRICKS);
        Reg("bricks", "pillar/bricks", PILLAR_BRICKS);
        Reg("bricks", "prism/bricks", PRISM_BRICKS);
        Reg("bricks", "raw/bricks", RAW_BRICKS);
        Reg("bricks", "road/bricks", ROAD_BRICKS);
        Reg("bricks", "slant/bricks", SLANT_BRICKS);
        Reg("bricks", "small_bricks/bricks", SMALL_BRICKS_BRICKS);
        Reg("bricks", "soft_bricks/bricks", SOFT_BRICKS_BRICKS);
        Reg("bricks", "solid_bricks/bricks", SOLID_BRICKS_BRICKS);
        Reg("bricks", "tiles_medium/bricks", TILES_MEDIUM_BRICKS);
        Reg("bricks", "tiles_small/bricks", TILES_SMALL_BRICKS);
        Reg("bricks", "triple_bricks/bricks", TRIPLE_BRICKS_BRICKS);
        Reg("bricks", "twist/bricks", TWIST_BRICKS);
        Reg("bricks", "weaver/bricks", WEAVER_BRICKS);
        Reg("bricks", "zag/bricks", ZAG_BRICKS);
        Reg("coal_block", "array/coal_block", ARRAY_COAL_BLOCK);
        Reg("coal_block", "braid/coal_block", BRAID_COAL_BLOCK);
        Reg("coal_block", "chaotic_bricks/coal_block", CHAOTIC_BRICKS_COAL_BLOCK);
        Reg("coal_block", "chaotic_medium/coal_block", CHAOTIC_MEDIUM_COAL_BLOCK);
        Reg("coal_block", "chaotic_small/coal_block", CHAOTIC_SMALL_COAL_BLOCK);
        Reg("coal_block", "circular/coal_block", CIRCULAR_COAL_BLOCK);
        Reg("coal_block", "cracked/coal_block", CRACKED_COAL_BLOCK);
        Reg("coal_block", "cracked_bricks/coal_block", CRACKED_BRICKS_COAL_BLOCK);
        Reg("coal_block", "cut/coal_block", CUT_COAL_BLOCK);
        Reg("coal_block", "dent/coal_block", DENT_COAL_BLOCK);
        Reg("coal_block", "encased_bricks/coal_block", ENCASED_BRICKS_COAL_BLOCK);
        Reg("coal_block", "french/coal_block", FRENCH_COAL_BLOCK);
        Reg("coal_block", "jellybean/coal_block", JELLYBEAN_COAL_BLOCK);
        Reg("coal_block", "large_bricks/coal_block", LARGE_BRICKS_COAL_BLOCK);
        Reg("coal_block", "large_tile/coal_block", LARGE_TILE_COAL_BLOCK);
        Reg("coal_block", "masonry/coal_block", MASONRY_COAL_BLOCK);
        Reg("coal_block", "mosaic/coal_block", MOSAIC_COAL_BLOCK);
        Reg("coal_block", "ornate/coal_block", ORNATE_COAL_BLOCK);
        Reg("coal_block", "panel/coal_block", PANEL_COAL_BLOCK);
        Reg("coal_block", "pillar/coal_block", PILLAR_COAL_BLOCK);
        Reg("coal_block", "prism/coal_block", PRISM_COAL_BLOCK);
        Reg("coal_block", "raw/coal_block", RAW_COAL_BLOCK);
        Reg("coal_block", "road/coal_block", ROAD_COAL_BLOCK);
        Reg("coal_block", "slant/coal_block", SLANT_COAL_BLOCK);
        Reg("coal_block", "small_bricks/coal_block", SMALL_BRICKS_COAL_BLOCK);
        Reg("coal_block", "soft_bricks/coal_block", SOFT_BRICKS_COAL_BLOCK);
        Reg("coal_block", "solid_bricks/coal_block", SOLID_BRICKS_COAL_BLOCK);
        Reg("coal_block", "tiles_medium/coal_block", TILES_MEDIUM_COAL_BLOCK);
        Reg("coal_block", "tiles_small/coal_block", TILES_SMALL_COAL_BLOCK);
        Reg("coal_block", "triple_bricks/coal_block", TRIPLE_BRICKS_COAL_BLOCK);
        Reg("coal_block", "twist/coal_block", TWIST_COAL_BLOCK);
        Reg("coal_block", "weaver/coal_block", WEAVER_COAL_BLOCK);
        Reg("coal_block", "zag/coal_block", ZAG_COAL_BLOCK);
        Reg("cobblestone", "array/cobblestone", ARRAY_COBBLESTONE);
        Reg("cobblestone", "braid/cobblestone", BRAID_COBBLESTONE);
        Reg("cobblestone", "chaotic_bricks/cobblestone", CHAOTIC_BRICKS_COBBLESTONE);
        Reg("cobblestone", "chaotic_medium/cobblestone", CHAOTIC_MEDIUM_COBBLESTONE);
        Reg("cobblestone", "chaotic_small/cobblestone", CHAOTIC_SMALL_COBBLESTONE);
        Reg("cobblestone", "circular/cobblestone", CIRCULAR_COBBLESTONE);
        Reg("cobblestone", "cracked/cobblestone", CRACKED_COBBLESTONE);
        Reg("cobblestone", "cracked_bricks/cobblestone", CRACKED_BRICKS_COBBLESTONE);
        Reg("cobblestone", "cut/cobblestone", CUT_COBBLESTONE);
        Reg("cobblestone", "dent/cobblestone", DENT_COBBLESTONE);
        Reg("cobblestone", "encased_bricks/cobblestone", ENCASED_BRICKS_COBBLESTONE);
        Reg("cobblestone", "french/cobblestone", FRENCH_COBBLESTONE);
        Reg("cobblestone", "jellybean/cobblestone", JELLYBEAN_COBBLESTONE);
        Reg("cobblestone", "large_tile/cobblestone", LARGE_TILE_COBBLESTONE);
        Reg("cobblestone", "layer/cobblestone", LAYER_COBBLESTONE);
        Reg("cobblestone", "mosaic/cobblestone", MOSAIC_COBBLESTONE);
        Reg("cobblestone", "ornate/cobblestone", ORNATE_COBBLESTONE);
        Reg("cobblestone", "panel/cobblestone", PANEL_COBBLESTONE);
        Reg("cobblestone", "pillar/cobblestone", PILLAR_COBBLESTONE);
        Reg("cobblestone", "prism/cobblestone", PRISM_COBBLESTONE);
        Reg("cobblestone", "raw/cobblestone", RAW_COBBLESTONE);
        Reg("cobblestone", "road/cobblestone", ROAD_COBBLESTONE);
        Reg("cobblestone", "slant/cobblestone", SLANT_COBBLESTONE);
        Reg("cobblestone", "small_bricks/cobblestone", SMALL_BRICKS_COBBLESTONE);
        Reg("cobblestone", "soft_bricks/cobblestone", SOFT_BRICKS_COBBLESTONE);
        Reg("cobblestone", "solid_bricks/cobblestone", SOLID_BRICKS_COBBLESTONE);
        Reg("cobblestone", "tiles_medium/cobblestone", TILES_MEDIUM_COBBLESTONE);
        Reg("cobblestone", "tiles_small/cobblestone", TILES_SMALL_COBBLESTONE);
        Reg("cobblestone", "triple_bricks/cobblestone", TRIPLE_BRICKS_COBBLESTONE);
        Reg("cobblestone", "twist/cobblestone", TWIST_COBBLESTONE);
        Reg("cobblestone", "weaver/cobblestone", WEAVER_COBBLESTONE);
        Reg("cobblestone", "zag/cobblestone", ZAG_COBBLESTONE);
        Reg("deepslate", "mosaic/deepslate", MOSAIC_DEEPSLATE);
        Reg("deepslate", "pillar/deepslate", PILLAR_DEEPSLATE);
        Reg("deepslate", "slant/deepslate", SLANT_DEEPSLATE);
        Reg("diamond_block", "bismuth/diamond_block", BISMUTH_DIAMOND_BLOCK);
        Reg("diamond_block", "cells/diamond_block", CELLS_DIAMOND_BLOCK);
        Reg("diamond_block", "crushed/diamond_block", CRUSHED_DIAMOND_BLOCK);
        Reg("diamond_block", "embossed/diamond_block", EMBOSSED_DIAMOND_BLOCK);
        Reg("diamond_block", "four/diamond_block", FOUR_DIAMOND_BLOCK);
        Reg("diamond_block", "fourornate/diamond_block", FOURORNATE_DIAMOND_BLOCK);
        Reg("diamond_block", "gem/diamond_block", GEM_DIAMOND_BLOCK);
        Reg("diamond_block", "ornatelayer/diamond_block", ORNATELAYER_DIAMOND_BLOCK);
        Reg("diamond_block", "simple/diamond_block", SIMPLE_DIAMOND_BLOCK);
        Reg("diamond_block", "space/diamond_block", SPACE_DIAMOND_BLOCK);
        Reg("diamond_block", "spaceblack/diamond_block", SPACEBLACK_DIAMOND_BLOCK);
        Reg("diamond_block", "zelda/diamond_block", ZELDA_DIAMOND_BLOCK);
        Reg("diorite", "array/diorite", ARRAY_DIORITE);
        Reg("diorite", "braid/diorite", BRAID_DIORITE);
        Reg("diorite", "chaotic_bricks/diorite", CHAOTIC_BRICKS_DIORITE);
        Reg("diorite", "chaotic_medium/diorite", CHAOTIC_MEDIUM_DIORITE);
        Reg("diorite", "chaotic_small/diorite", CHAOTIC_SMALL_DIORITE);
        Reg("diorite", "circular/diorite", CIRCULAR_DIORITE);
        Reg("diorite", "cracked/diorite", CRACKED_DIORITE);
        Reg("diorite", "cracked_bricks/diorite", CRACKED_BRICKS_DIORITE);
        Reg("diorite", "cut/diorite", CUT_DIORITE);
        Reg("diorite", "dent/diorite", DENT_DIORITE);
        Reg("diorite", "encased_bricks/diorite", ENCASED_BRICKS_DIORITE);
        Reg("diorite", "french/diorite", FRENCH_DIORITE);
        Reg("diorite", "jellybean/diorite", JELLYBEAN_DIORITE);
        Reg("diorite", "large_tile/diorite", LARGE_TILE_DIORITE);
        Reg("diorite", "layer/diorite", LAYER_DIORITE);
        Reg("diorite", "mosaic/diorite", MOSAIC_DIORITE);
        Reg("diorite", "ornate/diorite", ORNATE_DIORITE);
        Reg("diorite", "panel/diorite", PANEL_DIORITE);
        Reg("diorite", "pillar/diorite", PILLAR_DIORITE);
        Reg("diorite", "prism/diorite", PRISM_DIORITE);
        Reg("diorite", "raw/diorite", RAW_DIORITE);
        Reg("diorite", "road/diorite", ROAD_DIORITE);
        Reg("diorite", "slant/diorite", SLANT_DIORITE);
        Reg("diorite", "small_bricks/diorite", SMALL_BRICKS_DIORITE);
        Reg("diorite", "soft_bricks/diorite", SOFT_BRICKS_DIORITE);
        Reg("diorite", "solid_bricks/diorite", SOLID_BRICKS_DIORITE);
        Reg("diorite", "tiles_medium/diorite", TILES_MEDIUM_DIORITE);
        Reg("diorite", "tiles_small/diorite", TILES_SMALL_DIORITE);
        Reg("diorite", "triple_bricks/diorite", TRIPLE_BRICKS_DIORITE);
        Reg("diorite", "twist/diorite", TWIST_DIORITE);
        Reg("diorite", "weaver/diorite", WEAVER_DIORITE);
        Reg("diorite", "zag/diorite", ZAG_DIORITE);
        Reg("dirt", "bricks/dirt", BRICKS_DIRT);
        Reg("dirt", "bricks2/dirt", BRICKS2_DIRT);
        Reg("dirt", "bricks3/dirt", BRICKS3_DIRT);
        Reg("dirt", "chunky/dirt", CHUNKY_DIRT);
        Reg("dirt", "cobble/dirt", COBBLE_DIRT);
        Reg("dirt", "happy/dirt", HAPPY_DIRT);
        Reg("dirt", "horizontal/dirt", HORIZONTAL_DIRT);
        Reg("dirt", "layer/dirt", LAYER_DIRT);
        Reg("dirt", "panel/dirt", PANEL_DIRT);
        Reg("dirt", "reinforced/dirt", REINFORCED_DIRT);
        Reg("dirt", "reinforcedcobble/dirt", REINFORCEDCOBBLE_DIRT);
        Reg("dirt", "vertical/dirt", VERTICAL_DIRT);
        Reg("emerald_block", "bismuth/emerald_block", BISMUTH_EMERALD_BLOCK);
        Reg("emerald_block", "cells/emerald_block", CELLS_EMERALD_BLOCK);
        Reg("emerald_block", "chunky/emerald_block", CHUNKY_EMERALD_BLOCK);
        Reg("emerald_block", "circular/emerald_block", CIRCULAR_EMERALD_BLOCK);
        Reg("emerald_block", "four/emerald_block", FOUR_EMERALD_BLOCK);
        Reg("emerald_block", "fourornate/emerald_block", FOURORNATE_EMERALD_BLOCK);
        Reg("emerald_block", "goldborder/emerald_block", GOLDBORDER_EMERALD_BLOCK);
        Reg("emerald_block", "masonry/emerald_block", MASONRY_EMERALD_BLOCK);
        Reg("emerald_block", "ornate/emerald_block", ORNATE_EMERALD_BLOCK);
        Reg("emerald_block", "panel/emerald_block", PANEL_EMERALD_BLOCK);
        Reg("emerald_block", "panelclassic/emerald_block", PANELCLASSIC_EMERALD_BLOCK);
        Reg("emerald_block", "prism/emerald_block", PRISM_EMERALD_BLOCK);
        Reg("emerald_block", "smooth/emerald_block", SMOOTH_EMERALD_BLOCK);
        Reg("emerald_block", "zelda/emerald_block", ZELDA_EMERALD_BLOCK);
        Reg("end_stone", "array/end_stone", ARRAY_END_STONE);
        Reg("end_stone", "braid/end_stone", BRAID_END_STONE);
        Reg("end_stone", "chaotic_bricks/end_stone", CHAOTIC_BRICKS_END_STONE);
        Reg("end_stone", "chaotic_medium/end_stone", CHAOTIC_MEDIUM_END_STONE);
        Reg("end_stone", "chaotic_small/end_stone", CHAOTIC_SMALL_END_STONE);
        Reg("end_stone", "circular/end_stone", CIRCULAR_END_STONE);
        Reg("end_stone", "cracked/end_stone", CRACKED_END_STONE);
        Reg("end_stone", "cracked_bricks/end_stone", CRACKED_BRICKS_END_STONE);
        Reg("end_stone", "cut/end_stone", CUT_END_STONE);
        Reg("end_stone", "dent/end_stone", DENT_END_STONE);
        Reg("end_stone", "encased_bricks/end_stone", ENCASED_BRICKS_END_STONE);
        Reg("end_stone", "french/end_stone", FRENCH_END_STONE);
        Reg("end_stone", "jellybean/end_stone", JELLYBEAN_END_STONE);
        Reg("end_stone", "large_tile/end_stone", LARGE_TILE_END_STONE);
        Reg("end_stone", "layer/end_stone", LAYER_END_STONE);
        Reg("end_stone", "mosaic/end_stone", MOSAIC_END_STONE);
        Reg("end_stone", "ornate/end_stone", ORNATE_END_STONE);
        Reg("end_stone", "panel/end_stone", PANEL_END_STONE);
        Reg("end_stone", "pillar/end_stone", PILLAR_END_STONE);
        Reg("end_stone", "prism/end_stone", PRISM_END_STONE);
        Reg("end_stone", "raw/end_stone", RAW_END_STONE);
        Reg("end_stone", "road/end_stone", ROAD_END_STONE);
        Reg("end_stone", "slant/end_stone", SLANT_END_STONE);
        Reg("end_stone", "small_bricks/end_stone", SMALL_BRICKS_END_STONE);
        Reg("end_stone", "soft_bricks/end_stone", SOFT_BRICKS_END_STONE);
        Reg("end_stone", "solid_bricks/end_stone", SOLID_BRICKS_END_STONE);
        Reg("end_stone", "tiles_medium/end_stone", TILES_MEDIUM_END_STONE);
        Reg("end_stone", "tiles_small/end_stone", TILES_SMALL_END_STONE);
        Reg("end_stone", "triple_bricks/end_stone", TRIPLE_BRICKS_END_STONE);
        Reg("end_stone", "twist/end_stone", TWIST_END_STONE);
        Reg("end_stone", "weaver/end_stone", WEAVER_END_STONE);
        Reg("end_stone", "zag/end_stone", ZAG_END_STONE);
        Reg("glowstone", "array/glowstone", ARRAY_GLOWSTONE);
        Reg("glowstone", "bismuth/glowstone", BISMUTH_GLOWSTONE);
        Reg("glowstone", "braid/glowstone", BRAID_GLOWSTONE);
        Reg("glowstone", "chaotic_medium/glowstone", CHAOTIC_MEDIUM_GLOWSTONE);
        Reg("glowstone", "chaotic_small/glowstone", CHAOTIC_SMALL_GLOWSTONE);
        Reg("glowstone", "circular/glowstone", CIRCULAR_GLOWSTONE);
        Reg("glowstone", "cracked/glowstone", CRACKED_GLOWSTONE);
        Reg("glowstone", "cracked_bricks/glowstone", CRACKED_BRICKS_GLOWSTONE);
        Reg("glowstone", "dent/glowstone", DENT_GLOWSTONE);
        Reg("glowstone", "encased_bricks/glowstone", ENCASED_BRICKS_GLOWSTONE);
        Reg("glowstone", "french/glowstone", FRENCH_GLOWSTONE);
        Reg("glowstone", "jellybean/glowstone", JELLYBEAN_GLOWSTONE);
        Reg("glowstone", "large_tile/glowstone", LARGE_TILE_GLOWSTONE);
        Reg("glowstone", "large_tile_bismuth/glowstone", LARGE_TILE_BISMUTH_GLOWSTONE);
        Reg("glowstone", "layer/glowstone", LAYER_GLOWSTONE);
        Reg("glowstone", "mosaic/glowstone", MOSAIC_GLOWSTONE);
        Reg("glowstone", "neon/glowstone", NEON_GLOWSTONE);
        Reg("glowstone", "neon_panel/glowstone", NEON_PANEL_GLOWSTONE);
        Reg("glowstone", "ornate/glowstone", ORNATE_GLOWSTONE);
        Reg("glowstone", "panel/glowstone", PANEL_GLOWSTONE);
        Reg("glowstone", "pillar/glowstone", PILLAR_GLOWSTONE);
        Reg("glowstone", "prism/glowstone", PRISM_GLOWSTONE);
        Reg("glowstone", "road/glowstone", ROAD_GLOWSTONE);
        Reg("glowstone", "slant/glowstone", SLANT_GLOWSTONE);
        Reg("glowstone", "small_bricks/glowstone", SMALL_BRICKS_GLOWSTONE);
        Reg("glowstone", "soft_bricks/glowstone", SOFT_BRICKS_GLOWSTONE);
        Reg("glowstone", "solid_bricks/glowstone", SOLID_BRICKS_GLOWSTONE);
        Reg("glowstone", "tiles_medium/glowstone", TILES_MEDIUM_GLOWSTONE);
        Reg("glowstone", "tiles_medium_bismuth/glowstone", TILES_MEDIUM_BISMUTH_GLOWSTONE);
        Reg("glowstone", "tiles_small/glowstone", TILES_SMALL_GLOWSTONE);
        Reg("glowstone", "triple_bricks/glowstone", TRIPLE_BRICKS_GLOWSTONE);
        Reg("glowstone", "twist/glowstone", TWIST_GLOWSTONE);
        Reg("gold_block", "brick/gold_block", BRICK_GOLD_BLOCK);
        Reg("gold_block", "cart/gold_block", CART_GOLD_BLOCK);
        Reg("gold_block", "coin_heads/gold_block", COIN_HEADS_GOLD_BLOCK);
        Reg("gold_block", "coin_tails/gold_block", COIN_TAILS_GOLD_BLOCK);
        Reg("gold_block", "crate_dark/gold_block", CRATE_DARK_GOLD_BLOCK);
        Reg("gold_block", "crate_light/gold_block", CRATE_LIGHT_GOLD_BLOCK);
        Reg("gold_block", "largeingot/gold_block", LARGEINGOT_GOLD_BLOCK);
        Reg("gold_block", "plates/gold_block", PLATES_GOLD_BLOCK);
        Reg("gold_block", "rivets/gold_block", RIVETS_GOLD_BLOCK);
        Reg("gold_block", "simple/gold_block", SIMPLE_GOLD_BLOCK);
        Reg("gold_block", "smallingot/gold_block", SMALLINGOT_GOLD_BLOCK);
        Reg("gold_block", "space/gold_block", SPACE_GOLD_BLOCK);
        Reg("gold_block", "spaceblack/gold_block", SPACEBLACK_GOLD_BLOCK);
        Reg("gold_block", "star/gold_block", STAR_GOLD_BLOCK);
        Reg("granite", "array/granite", ARRAY_GRANITE);
        Reg("granite", "braid/granite", BRAID_GRANITE);
        Reg("granite", "chaotic_bricks/granite", CHAOTIC_BRICKS_GRANITE);
        Reg("granite", "chaotic_medium/granite", CHAOTIC_MEDIUM_GRANITE);
        Reg("granite", "chaotic_small/granite", CHAOTIC_SMALL_GRANITE);
        Reg("granite", "circular/granite", CIRCULAR_GRANITE);
        Reg("granite", "cracked/granite", CRACKED_GRANITE);
        Reg("granite", "cracked_bricks/granite", CRACKED_BRICKS_GRANITE);
        Reg("granite", "cut/granite", CUT_GRANITE);
        Reg("granite", "dent/granite", DENT_GRANITE);
        Reg("granite", "encased_bricks/granite", ENCASED_BRICKS_GRANITE);
        Reg("granite", "french/granite", FRENCH_GRANITE);
        Reg("granite", "jellybean/granite", JELLYBEAN_GRANITE);
        Reg("granite", "large_tile/granite", LARGE_TILE_GRANITE);
        Reg("granite", "layer/granite", LAYER_GRANITE);
        Reg("granite", "mosaic/granite", MOSAIC_GRANITE);
        Reg("granite", "ornate/granite", ORNATE_GRANITE);
        Reg("granite", "panel/granite", PANEL_GRANITE);
        Reg("granite", "pillar/granite", PILLAR_GRANITE);
        Reg("granite", "prism/granite", PRISM_GRANITE);
        Reg("granite", "raw/granite", RAW_GRANITE);
        Reg("granite", "road/granite", ROAD_GRANITE);
        Reg("granite", "slant/granite", SLANT_GRANITE);
        Reg("granite", "small_bricks/granite", SMALL_BRICKS_GRANITE);
        Reg("granite", "soft_bricks/granite", SOFT_BRICKS_GRANITE);
        Reg("granite", "solid_bricks/granite", SOLID_BRICKS_GRANITE);
        Reg("granite", "tiles_medium/granite", TILES_MEDIUM_GRANITE);
        Reg("granite", "tiles_small/granite", TILES_SMALL_GRANITE);
        Reg("granite", "triple_bricks/granite", TRIPLE_BRICKS_GRANITE);
        Reg("granite", "twist/granite", TWIST_GRANITE);
        Reg("granite", "weaver/granite", WEAVER_GRANITE);
        Reg("granite", "zag/granite", ZAG_GRANITE);
        Reg("iron_block", "brick/iron_block", BRICK_IRON_BLOCK);
        Reg("iron_block", "coin_heads/iron_block", COIN_HEADS_IRON_BLOCK);
        Reg("iron_block", "coin_tails/iron_block", COIN_TAILS_IRON_BLOCK);
        Reg("iron_block", "crate_dark/iron_block", CRATE_DARK_IRON_BLOCK);
        Reg("iron_block", "crate_light/iron_block", CRATE_LIGHT_IRON_BLOCK);
        Reg("iron_block", "gears/iron_block", GEARS_IRON_BLOCK);
        Reg("iron_block", "largeingot/iron_block", LARGEINGOT_IRON_BLOCK);
        Reg("iron_block", "moon/iron_block", MOON_IRON_BLOCK);
        Reg("iron_block", "plates/iron_block", PLATES_IRON_BLOCK);
        Reg("iron_block", "rivets/iron_block", RIVETS_IRON_BLOCK);
        Reg("iron_block", "simple/iron_block", SIMPLE_IRON_BLOCK);
        Reg("iron_block", "smallingot/iron_block", SMALLINGOT_IRON_BLOCK);
        Reg("iron_block", "space/iron_block", SPACE_IRON_BLOCK);
        Reg("iron_block", "spaceblack/iron_block", SPACEBLACK_IRON_BLOCK);
        Reg("iron_block", "vents/iron_block", VENTS_IRON_BLOCK);
        Reg("lapis_block", "chunky/lapis_block", CHUNKY_LAPIS_BLOCK);
        Reg("lapis_block", "large_tile/lapis_block", LARGE_TILE_LAPIS_BLOCK);
        Reg("lapis_block", "masonry/lapis_block", MASONRY_LAPIS_BLOCK);
        Reg("lapis_block", "ornate/lapis_block", ORNATE_LAPIS_BLOCK);
        Reg("lapis_block", "ornatelayer/lapis_block", ORNATELAYER_LAPIS_BLOCK);
        Reg("lapis_block", "panel/lapis_block", PANEL_LAPIS_BLOCK);
        Reg("lapis_block", "panelclassic/lapis_block", PANELCLASSIC_LAPIS_BLOCK);
        Reg("lapis_block", "smooth/lapis_block", SMOOTH_LAPIS_BLOCK);
        Reg("lapis_block", "zelda/lapis_block", ZELDA_LAPIS_BLOCK);
        Reg("nether_brick", "mosaic/nether_brick", MOSAIC_NETHER_BRICK);
        Reg("nether_brick", "pillar/nether_brick", PILLAR_NETHER_BRICK);
        Reg("nether_brick", "slant/nether_brick", SLANT_NETHER_BRICK);
        Reg("purpur", "array/purpur", ARRAY_PURPUR);
        Reg("purpur", "braid/purpur", BRAID_PURPUR);
        Reg("purpur", "chaotic_bricks/purpur", CHAOTIC_BRICKS_PURPUR);
        Reg("purpur", "chaotic_medium/purpur", CHAOTIC_MEDIUM_PURPUR);
        Reg("purpur", "chaotic_small/purpur", CHAOTIC_SMALL_PURPUR);
        Reg("purpur", "circular/purpur", CIRCULAR_PURPUR);
        Reg("purpur", "cracked/purpur", CRACKED_PURPUR);
        Reg("purpur", "cracked_bricks/purpur", CRACKED_BRICKS_PURPUR);
        Reg("purpur", "cut/purpur", CUT_PURPUR);
        Reg("purpur", "dent/purpur", DENT_PURPUR);
        Reg("purpur", "encased_bricks/purpur", ENCASED_BRICKS_PURPUR);
        Reg("purpur", "french/purpur", FRENCH_PURPUR);
        Reg("purpur", "jellybean/purpur", JELLYBEAN_PURPUR);
        Reg("purpur", "large_tile/purpur", LARGE_TILE_PURPUR);
        Reg("purpur", "layer/purpur", LAYER_PURPUR);
        Reg("purpur", "mosaic/purpur", MOSAIC_PURPUR);
        Reg("purpur", "ornate/purpur", ORNATE_PURPUR);
        Reg("purpur", "panel/purpur", PANEL_PURPUR);
        Reg("purpur", "pillar/purpur", PILLAR_PURPUR);
        Reg("purpur", "prism/purpur", PRISM_PURPUR);
        Reg("purpur", "raw/purpur", RAW_PURPUR);
        Reg("purpur", "road/purpur", ROAD_PURPUR);
        Reg("purpur", "slant/purpur", SLANT_PURPUR);
        Reg("purpur", "small_bricks/purpur", SMALL_BRICKS_PURPUR);
        Reg("purpur", "soft_bricks/purpur", SOFT_BRICKS_PURPUR);
        Reg("purpur", "solid_bricks/purpur", SOLID_BRICKS_PURPUR);
        Reg("purpur", "tiles_medium/purpur", TILES_MEDIUM_PURPUR);
        Reg("purpur", "tiles_small/purpur", TILES_SMALL_PURPUR);
        Reg("purpur", "triple_bricks/purpur", TRIPLE_BRICKS_PURPUR);
        Reg("purpur", "twist/purpur", TWIST_PURPUR);
        Reg("purpur", "weaver/purpur", WEAVER_PURPUR);
        Reg("purpur", "zag/purpur", ZAG_PURPUR);
        Reg("quartz", "array/quartz", ARRAY_QUARTZ);
        Reg("quartz", "braid/quartz", BRAID_QUARTZ);
        Reg("quartz", "chaotic_bricks/quartz", CHAOTIC_BRICKS_QUARTZ);
        Reg("quartz", "chaotic_medium/quartz", CHAOTIC_MEDIUM_QUARTZ);
        Reg("quartz", "chaotic_small/quartz", CHAOTIC_SMALL_QUARTZ);
        Reg("quartz", "circular/quartz", CIRCULAR_QUARTZ);
        Reg("quartz", "cracked/quartz", CRACKED_QUARTZ);
        Reg("quartz", "cracked_bricks/quartz", CRACKED_BRICKS_QUARTZ);
        Reg("quartz", "cut/quartz", CUT_QUARTZ);
        Reg("quartz", "dent/quartz", DENT_QUARTZ);
        Reg("quartz", "encased_bricks/quartz", ENCASED_BRICKS_QUARTZ);
        Reg("quartz", "french/quartz", FRENCH_QUARTZ);
        Reg("quartz", "jellybean/quartz", JELLYBEAN_QUARTZ);
        Reg("quartz", "large_tile/quartz", LARGE_TILE_QUARTZ);
        Reg("quartz", "layer/quartz", LAYER_QUARTZ);
        Reg("quartz", "mosaic/quartz", MOSAIC_QUARTZ);
        Reg("quartz", "ornate/quartz", ORNATE_QUARTZ);
        Reg("quartz", "panel/quartz", PANEL_QUARTZ);
        Reg("quartz", "pillar/quartz", PILLAR_QUARTZ);
        Reg("quartz", "prism/quartz", PRISM_QUARTZ);
        Reg("quartz", "raw/quartz", RAW_QUARTZ);
        Reg("quartz", "road/quartz", ROAD_QUARTZ);
        Reg("quartz", "slant/quartz", SLANT_QUARTZ);
        Reg("quartz", "small_bricks/quartz", SMALL_BRICKS_QUARTZ);
        Reg("quartz", "soft_bricks/quartz", SOFT_BRICKS_QUARTZ);
        Reg("quartz", "solid_bricks/quartz", SOLID_BRICKS_QUARTZ);
        Reg("quartz", "tiles_medium/quartz", TILES_MEDIUM_QUARTZ);
        Reg("quartz", "tiles_small/quartz", TILES_SMALL_QUARTZ);
        Reg("quartz", "triple_bricks/quartz", TRIPLE_BRICKS_QUARTZ);
        Reg("quartz", "twist/quartz", TWIST_QUARTZ);
        Reg("quartz", "weaver/quartz", WEAVER_QUARTZ);
        Reg("quartz", "zag/quartz", ZAG_QUARTZ);
        Reg("red_sandstone", "array/red_sandstone", ARRAY_RED_SANDSTONE);
        Reg("red_sandstone", "bevel_skeleton/red_sandstone", BEVEL_SKELETON_RED_SANDSTONE);
        Reg("red_sandstone", "braid/red_sandstone", BRAID_RED_SANDSTONE);
        Reg("red_sandstone", "chaotic_bricks/red_sandstone", CHAOTIC_BRICKS_RED_SANDSTONE);
        Reg("red_sandstone", "chaotic_medium/red_sandstone", CHAOTIC_MEDIUM_RED_SANDSTONE);
        Reg("red_sandstone", "chaotic_small/red_sandstone", CHAOTIC_SMALL_RED_SANDSTONE);
        Reg("red_sandstone", "circular/red_sandstone", CIRCULAR_RED_SANDSTONE);
        Reg("red_sandstone", "cracked/red_sandstone", CRACKED_RED_SANDSTONE);
        Reg("red_sandstone", "cracked_bricks/red_sandstone", CRACKED_BRICKS_RED_SANDSTONE);
        Reg("red_sandstone", "cut/red_sandstone", CUT_RED_SANDSTONE);
        Reg("red_sandstone", "dent/red_sandstone", DENT_RED_SANDSTONE);
        Reg("red_sandstone", "encased_bricks/red_sandstone", ENCASED_BRICKS_RED_SANDSTONE);
        Reg("red_sandstone", "french/red_sandstone", FRENCH_RED_SANDSTONE);
        Reg("red_sandstone", "glyphs/red_sandstone", GLYPHS_RED_SANDSTONE);
        Reg("red_sandstone", "jellybean/red_sandstone", JELLYBEAN_RED_SANDSTONE);
        Reg("red_sandstone", "large_tile/red_sandstone", LARGE_TILE_RED_SANDSTONE);
        Reg("red_sandstone", "layer/red_sandstone", LAYER_RED_SANDSTONE);
        Reg("red_sandstone", "mosaic/red_sandstone", MOSAIC_RED_SANDSTONE);
        Reg("red_sandstone", "ornate/red_sandstone", ORNATE_RED_SANDSTONE);
        Reg("red_sandstone", "panel/red_sandstone", PANEL_RED_SANDSTONE);
        Reg("red_sandstone", "pillar/red_sandstone", PILLAR_RED_SANDSTONE);
        Reg("red_sandstone", "prism/red_sandstone", PRISM_RED_SANDSTONE);
        Reg("red_sandstone", "raw/red_sandstone", RAW_RED_SANDSTONE);
        Reg("red_sandstone", "road/red_sandstone", ROAD_RED_SANDSTONE);
        Reg("red_sandstone", "slant/red_sandstone", SLANT_RED_SANDSTONE);
        Reg("red_sandstone", "small/red_sandstone", SMALL_RED_SANDSTONE);
        Reg("red_sandstone", "small_bricks/red_sandstone", SMALL_BRICKS_RED_SANDSTONE);
        Reg("red_sandstone", "soft_bricks/red_sandstone", SOFT_BRICKS_RED_SANDSTONE);
        Reg("red_sandstone", "solid_bricks/red_sandstone", SOLID_BRICKS_RED_SANDSTONE);
        Reg("red_sandstone", "tiles_medium/red_sandstone", TILES_MEDIUM_RED_SANDSTONE);
        Reg("red_sandstone", "tiles_small/red_sandstone", TILES_SMALL_RED_SANDSTONE);
        Reg("red_sandstone", "triple_bricks/red_sandstone", TRIPLE_BRICKS_RED_SANDSTONE);
        Reg("red_sandstone", "twist/red_sandstone", TWIST_RED_SANDSTONE);
        Reg("red_sandstone", "weaver/red_sandstone", WEAVER_RED_SANDSTONE);
        Reg("red_sandstone", "zag/red_sandstone", ZAG_RED_SANDSTONE);
        Reg("redstone_block", "array/redstone_block", ARRAY_REDSTONE_BLOCK);
        Reg("redstone_block", "braid/redstone_block", BRAID_REDSTONE_BLOCK);
        Reg("redstone_block", "chaotic_medium/redstone_block", CHAOTIC_MEDIUM_REDSTONE_BLOCK);
        Reg("redstone_block", "chaotic_small/redstone_block", CHAOTIC_SMALL_REDSTONE_BLOCK);
        Reg("redstone_block", "circular/redstone_block", CIRCULAR_REDSTONE_BLOCK);
        Reg("redstone_block", "cracked/redstone_block", CRACKED_REDSTONE_BLOCK);
        Reg("redstone_block", "cracked_bricks/redstone_block", CRACKED_BRICKS_REDSTONE_BLOCK);
        Reg("redstone_block", "dent/redstone_block", DENT_REDSTONE_BLOCK);
        Reg("redstone_block", "encased_bricks/redstone_block", ENCASED_BRICKS_REDSTONE_BLOCK);
        Reg("redstone_block", "french/redstone_block", FRENCH_REDSTONE_BLOCK);
        Reg("redstone_block", "jellybean/redstone_block", JELLYBEAN_REDSTONE_BLOCK);
        Reg("redstone_block", "large_tile/redstone_block", LARGE_TILE_REDSTONE_BLOCK);
        Reg("redstone_block", "layer/redstone_block", LAYER_REDSTONE_BLOCK);
        Reg("redstone_block", "mosaic/redstone_block", MOSAIC_REDSTONE_BLOCK);
        Reg("redstone_block", "ornate/redstone_block", ORNATE_REDSTONE_BLOCK);
        Reg("redstone_block", "panel/redstone_block", PANEL_REDSTONE_BLOCK);
        Reg("redstone_block", "pillar/redstone_block", PILLAR_REDSTONE_BLOCK);
        Reg("redstone_block", "prism/redstone_block", PRISM_REDSTONE_BLOCK);
        Reg("redstone_block", "road/redstone_block", ROAD_REDSTONE_BLOCK);
        Reg("redstone_block", "slant/redstone_block", SLANT_REDSTONE_BLOCK);
        Reg("redstone_block", "small_bricks/redstone_block", SMALL_BRICKS_REDSTONE_BLOCK);
        Reg("redstone_block", "soft_bricks/redstone_block", SOFT_BRICKS_REDSTONE_BLOCK);
        Reg("redstone_block", "solid_bricks/redstone_block", SOLID_BRICKS_REDSTONE_BLOCK);
        Reg("redstone_block", "tiles_medium/redstone_block", TILES_MEDIUM_REDSTONE_BLOCK);
        Reg("redstone_block", "tiles_small/redstone_block", TILES_SMALL_REDSTONE_BLOCK);
        Reg("redstone_block", "triple_bricks/redstone_block", TRIPLE_BRICKS_REDSTONE_BLOCK);
        Reg("redstone_block", "twist/redstone_block", TWIST_REDSTONE_BLOCK);
        Reg("sandstone", "array/sandstone", ARRAY_SANDSTONE);
        Reg("sandstone", "bevel_creeper/sandstone", BEVEL_CREEPER_SANDSTONE);
        Reg("sandstone", "braid/sandstone", BRAID_SANDSTONE);
        Reg("sandstone", "chaotic_bricks/sandstone", CHAOTIC_BRICKS_SANDSTONE);
        Reg("sandstone", "chaotic_medium/sandstone", CHAOTIC_MEDIUM_SANDSTONE);
        Reg("sandstone", "chaotic_small/sandstone", CHAOTIC_SMALL_SANDSTONE);
        Reg("sandstone", "circular/sandstone", CIRCULAR_SANDSTONE);
        Reg("sandstone", "cracked/sandstone", CRACKED_SANDSTONE);
        Reg("sandstone", "cracked_bricks/sandstone", CRACKED_BRICKS_SANDSTONE);
        Reg("sandstone", "cut/sandstone", CUT_SANDSTONE);
        Reg("sandstone", "dent/sandstone", DENT_SANDSTONE);
        Reg("sandstone", "encased_bricks/sandstone", ENCASED_BRICKS_SANDSTONE);
        Reg("sandstone", "french/sandstone", FRENCH_SANDSTONE);
        Reg("sandstone", "glyphs/sandstone", GLYPHS_SANDSTONE);
        Reg("sandstone", "jellybean/sandstone", JELLYBEAN_SANDSTONE);
        Reg("sandstone", "large_tile/sandstone", LARGE_TILE_SANDSTONE);
        Reg("sandstone", "layer/sandstone", LAYER_SANDSTONE);
        Reg("sandstone", "mosaic/sandstone", MOSAIC_SANDSTONE);
        Reg("sandstone", "ornate/sandstone", ORNATE_SANDSTONE);
        Reg("sandstone", "panel/sandstone", PANEL_SANDSTONE);
        Reg("sandstone", "pillar/sandstone", PILLAR_SANDSTONE);
        Reg("sandstone", "prism/sandstone", PRISM_SANDSTONE);
        Reg("sandstone", "raw/sandstone", RAW_SANDSTONE);
        Reg("sandstone", "road/sandstone", ROAD_SANDSTONE);
        Reg("sandstone", "slant/sandstone", SLANT_SANDSTONE);
        Reg("sandstone", "small/sandstone", SMALL_SANDSTONE);
        Reg("sandstone", "small_bricks/sandstone", SMALL_BRICKS_SANDSTONE);
        Reg("sandstone", "soft_bricks/sandstone", SOFT_BRICKS_SANDSTONE);
        Reg("sandstone", "solid_bricks/sandstone", SOLID_BRICKS_SANDSTONE);
        Reg("sandstone", "tiles_medium/sandstone", TILES_MEDIUM_SANDSTONE);
        Reg("sandstone", "tiles_small/sandstone", TILES_SMALL_SANDSTONE);
        Reg("sandstone", "triple_bricks/sandstone", TRIPLE_BRICKS_SANDSTONE);
        Reg("sandstone", "twist/sandstone", TWIST_SANDSTONE);
        Reg("sandstone", "weaver/sandstone", WEAVER_SANDSTONE);
        Reg("sandstone", "zag/sandstone", ZAG_SANDSTONE);
        Reg("stone", "array/stone", ARRAY_STONE);
        Reg("stone", "braid/stone", BRAID_STONE);
        Reg("stone", "chaotic_bricks/stone", CHAOTIC_BRICKS_STONE);
        Reg("stone", "chaotic_medium/stone", CHAOTIC_MEDIUM_STONE);
        Reg("stone", "chaotic_small/stone", CHAOTIC_SMALL_STONE);
        Reg("stone", "circular/stone", CIRCULAR_STONE);
        Reg("stone", "cracked/stone", CRACKED_STONE);
        Reg("stone", "cracked_bricks/stone", CRACKED_BRICKS_STONE);
        Reg("stone", "cut/stone", CUT_STONE);
        Reg("stone", "dent/stone", DENT_STONE);
        Reg("stone", "encased_bricks/stone", ENCASED_BRICKS_STONE);
        Reg("stone", "french/stone", FRENCH_STONE);
        Reg("stone", "jellybean/stone", JELLYBEAN_STONE);
        Reg("stone", "large_tile/stone", LARGE_TILE_STONE);
        Reg("stone", "largeornate/stone", LARGEORNATE_STONE);
        Reg("stone", "layer/stone", LAYER_STONE);
        Reg("stone", "mosaic/stone", MOSAIC_STONE);
        Reg("stone", "ornate/stone", ORNATE_STONE);
        Reg("stone", "panel/stone", PANEL_STONE);
        Reg("stone", "pillar/stone", PILLAR_STONE);
        Reg("stone", "poison/stone", POISON_STONE);
        Reg("stone", "prism/stone", PRISM_STONE);
        Reg("stone", "raw/stone", RAW_STONE);
        Reg("stone", "road/stone", ROAD_STONE);
        Reg("stone", "slant/stone", SLANT_STONE);
        Reg("stone", "small_bricks/stone", SMALL_BRICKS_STONE);
        Reg("stone", "soft_bricks/stone", SOFT_BRICKS_STONE);
        Reg("stone", "solid_bricks/stone", SOLID_BRICKS_STONE);
        Reg("stone", "sunken/stone", SUNKEN_STONE);
        Reg("stone", "tiles_medium/stone", TILES_MEDIUM_STONE);
        Reg("stone", "tiles_small/stone", TILES_SMALL_STONE);
        Reg("stone", "triple_bricks/stone", TRIPLE_BRICKS_STONE);
        Reg("stone", "twist/stone", TWIST_STONE);
        Reg("stone", "weaver/stone", WEAVER_STONE);
        Reg("stone", "zag/stone", ZAG_STONE);
    }
}